CALL InsertarDatosArticulo('M Díaz-Canel Bermúdez', 
'¿Por qué necesitamos un sistema de gestión del Gobierno basado en ciencia e innovación?', 
2021,
'http://scielo.sld.cu/scielo.php?pid=S2304-01062021000100005&script=sci_arttext', 
'Uso de estrategias tecnológicas para continuar con la educación a pesar de los cierres de instituciones educativas. Ejemplos de estas innovaciones incluyen el uso de la plataforma CREA en Uruguay, la televisión educativa multigrado en México, plataformas educativas en Colombia, y "Aprendo en Línea" en Chile.', 
'Los efectos generados por estas intervenciones se describen como positivos, permitiendo la continuidad de la educación a pesar de la pandemia. Se observaron esfuerzos para mantener el aprendizaje a través de diferentes medios tecnológicos y tradicionales, como la televisión y la radio, y se menciona que la tecnología permitió cumplir con los objetivos académicos en diversos contextos.', 
'No se especifíca de forma suficiente la metodología empleada', 
'', 
'',
'',
'Cuba, Mexico, Costa Rica',
10, 
'Vinculacion');

CALL InsertarDatosArticulo('M Díaz-Canel Bermúdez, R Alarcón Ortiz', 
'Potencial humano, innovación y desarrollo en la planificación estratégica de la educación superior cubana 2012-2020', 
2020,
'http://scielo.sld.cu/scielo.php?pid=S0257-43142020000300001&script=sci_arttext', 
'Efectividad de la gestión universitaria del conocimiento y la innovación en Cuba, enfocándose en la integración de procesos universitarios y su vinculación con el sector productivo y los territorios para generar un mayor impacto económico y social. Esta intervención forma parte del Sistema de Ciencia Tecnología e Innovación (SCTI) y está alineada con la planificación estratégica de la educación superior entre 2012 y 2020​​.', 
'La intervención logró avances en la integración de procesos de formación y superación profesional, extensión universitaria, investigación e innovación, orientados al desarrollo local. Esto tuvo un impacto significativo en el 50% de los municipios cubanos durante el período 2012-2020, manteniendo su vigencia para futuras adecuaciones​​.', 
'No se especifíca de forma suficiente la metodología empleada', 
'', 
'',
'',
'Cuba',
73, 
'Vinculacion');

CALL InsertarDatosArticulo('GJB Rodríguez, JLA Suárez', 
'La educación de posgrado ante el nuevo escenario generado por la COVID-19', 
2020,
'https://www.medigraphic.com/cgi-bin/new/resumen.cgi?IDARTICULO=100575', 
'Implementación de programas de posgrado en modalidad a distancia, enfocándose en tres escenarios de conectividad: total, parcial o limitada, y sin conectividad. Esta intervención busca aprovechar las Tecnologías de la Información y la Comunicación (TIC) para ofrecer formación académica acreditada y de gran demanda a un número mayor de profesionales, de manera más económica y eficiente​​.', 
'Los efectos específicos de esta intervención no se describen detalladamente en el documento. Sin embargo, se infiere que la orientación de los programas de posgrado y la adaptación a la modalidad a distancia podrían generar impactos positivos en el desarrollo del país, así como en la solución de problemas globales y locales mediante trabajos finales y tesis enfocados en resultados válidos, sostenibles, aplicables e innovadores​​.', 
'No se especifíca de forma suficiente la metodología empleada', 
'Temporalidad', 
'Sesgos P',
'Sesgos M',
'Cuba',
50, 
'Vinculacion');

CALL InsertarDatosArticulo('LF Abreu-Hernández, R León-Bórquez', 
'Pandemia de COVID-19 y educación médica en Latinoamérica', 
2020,
'https://scielo.isciii.es/scielo.php?pid=S2014-98322020000600002&script=sci_arttext', 
'Migración de la educación médica a formatos virtuales, la implementación de telemedicina, la organización de brigadas de estudiantes voluntarios, y el fortalecimiento de la educación continua mediante tecnologías de la información y la comunicación (TIC)​​.', 
'Desafío de mantener la formación académica y la contribución a la respuesta a la pandemia, apoyados en las TIC. También se abordan las limitaciones y desafíos enfrentados por profesores y estudiantes durante la migración digital, incluyendo aspectos como la falta de ancho de banda suficiente y la carencia de equipos informáticos​​.', 
'No se especifíca de forma suficiente la metodología empleada', 
'', 
'',
'',
'Argentina, Bolivia, Costa Rica, Chile, Ecuador, México, Panamá, Perú, República Dominicana',
47, 
'Vinculacion');

CALL InsertarDatosArticulo('CB Videla, E Vázquez-Cano, E López-Meneses', 
'PROYECTO DIFPRORET: Análisis de las dificultades, propuestas y retos educativos ante el COVID-19', 
2021,
'https://www.upo.es/revistas/index.php/IJERI/article/view/5145', 
'Comunicación y redes entre estudiantes y profesores, el fomento de la autonomía y el desarrollo socioemocional, el trabajo colaborativo y la adaptación de estrategias educativas al contexto digital​​.', 
'No se detallan explícitamente los efectos generados por estas intervenciones. El enfoque está más en la descripción de las estrategias y su relevancia en el contexto de la pandemia​​.', 
'No se especifíca de forma suficiente la metodología empleada', 
'', 
'',
'',
'Brasil',
37, 
'Vinculacion');