CALL InsertarDatosArticulo('MJ Vidal Ledo', 
'Impacto de la COVID-19 en la Educación Superior', 
2021,
'http://scielo.sld.cu/scielo.php?pid=S0864-21412021000100023&script=sci_arttext&tlng=pt', 
'El documento describe una intervención innovadora en el contexto de la educación superior y la universidad, relacionada con el teletrabajo como respuesta a la pandemia de COVID-19.La innovación del teletrabajo, tal como se describe en el documento, se realizó en la Universidad Estatal a Distancia (UNED) en Costa Rica. El modelo de teletrabajo liderado por esta universidad estatal se menciona como un ejemplo de prácticas exitosas, especialmente en respuesta a la pandemia de COVID-19. ', 
'Destaca el uso de tecnologías para el trabajo a distancia, enfocándose en los beneficios como la flexibilidad horaria, facilitar el trabajo y la colaboración a distancia mediante el uso de tecnologías de la información y comunicación, y mejoras en los hábitos alimenticios y de salud general. La implementación del teletrabajo generó varios efectos, como un mayor ahorro de dinero, mejor aprovechamiento del tiempo, y un impacto positivo en la motivación y desempeño laboral. También se observa una disminución de estrés y un crecimiento profesional', 
'Estudio No Experimental Mediante Encuesta Basado en una Muestra No Representativa', 
'Transversal', 
'Sesgo de Recordatorio, Sesgo de Fatiga',
'Sesgo de Cobertura, Sesgo de Deseabilidad Social',
'Costa Rica',
62, 
'Movilidad');

CALL InsertarDatosArticulo('C Chanto Espinoza, J Loáiciga Gutiérrez', 
'Percepciones de estudiantes sobre el uso de la videoconferencia durante las clases virtuales a nivel universitario, en tiempos de COVID-19', 
2022,
'http://www.scielo.org.pe/scielo.php?pid=S1019-94032022000100054&script=sci_arttext', 
'El documento describe la transición de la movilidad académica y la internacionalización en la educación superior a modalidades virtuales debido a la pandemia. Esto generó un debate sobre la internacionalización del currículo como parte de una estrategia integral, y se implementaron programas de formación y fortalecimiento para instituciones educativas, abordando las problemáticas que la pandemia planteó para la internacionalización universitaria y las posibles respuestas a nivel sistémico​​.', 
'La transición a la virtualidad desencadenó cambios significativos en la educación superior. Entre estos, se resalta la instalación de un debate sobre la internacionalización del currículo y la generación de estructuras de respuesta ante situaciones de crisis. Se menciona también el desarrollo de protocolos para la contención psico-social y afectiva de becarios internacionales, y la regulación del reconocimiento de títulos y trayectos formativos, acelerando debates y madurando discursos regulatorios en el ámbito educativo​​.', 
'No se especifíca de forma suficiente la metodología empleada', 
'No se especifíca la temporalidad', 
'',
'',
'Ecuador, Brasil, Argentina',
6, 
'Movilidad');

CALL InsertarDatosArticulo('MGD Corte, MC Morosini, VL Felicetti', 
'Internacionalización de la Educación Superior en la Perspectiva Sur-Sur: Movimientos y Contextos Emergentes en Tiempos de Pandemia', 
2022,
'http://educa.fcc.org.br/scielo.php?pid=S2446-94242022000100109&script=sci_arttext', 
'El documento describe la Movilidad Virtual de Estudiantes (MVE) como una intervención innovadora en la internacionalización de la educación superior. La MVE utiliza tecnologías de información y comunicación para facilitar intercambios y colaboración académica, cultural y experiencial transfronteriza e interinstitucional. Se menciona que la MVE apoya la internacionalización de la educación superior haciéndola más inclusiva y sostenible, y promueve una educación de alta calidad y el desarrollo de competencias. La MVE ha sido impulsada como respuesta a la pandemia y se ve como un medio para reimaginar la movilidad de los estudiantes en un panorama pospandémico', 
'El documento señala que la MVE puede mejorar la equidad en la movilidad estudiantil al fomentar mayores tasas de participación. También aborda la calidad, tanto real como percibida, de la movilidad virtual y su potencial para ofrecer experiencias de alta calidad en términos académicos, de socialización e intercambios culturales. Se sugiere que la MVE podría incrementar el acceso a la educación internacional, aprovechar la tecnología de manera definitiva y reducir la huella medioambiental de la educación superior', 
'Estudio de Caso Cualitativo', 
'Transversal', 
'',
'Sesgo del Observador, Sesgo de Retrospección (Hindsight Bias), Sesgo de Narrativa',
'Venezuela',
4, 
'Movilidad');

CALL InsertarDatosArticulo('E Castro Monge', 
'Factores a considerar para una educación a distancia inclusiva', 
2023,
'http://scielo.iics.una.py/scielo.php?pid=S2414-89382023000100112&script=sci_arttext', 
'La investigación se basa en la Universidad de Ciencias Médicas de Camagüey, ubicada en Cuba. El documento describe varias intervenciones innovadoras relacionadas con la movilidad académica y la internacionalización en la educación superior. Entre ellas se destacan. Formación Doctoral y Desarrollo Especializado: La universidad ha establecido colaboraciones con entidades europeas y latinoamericanas para promover la formación doctoral y el desarrollo especializado. Esto incluye proyectos y estancias de investigación que contribuyen a la formación avanzada y al desarrollo de habilidades especializadas en áreas clave de la medicina y la salud pública. Estas colaboraciones internacionales facilitan el intercambio de conocimientos y experiencias, enriqueciendo así la formación académica y profesional de los estudiantes y profesores de la universidad. Participación en Redes Académicas y de Investigación: La Universidad de Ciencias Médicas de Camagüey se involucra activamente en redes académicas y de investigación, tanto a nivel nacional como internacional. Esto incluye la participación en eventos y conferencias, así como la contribución a publicaciones científicas. La activa participación en estas redes permite a la universidad mantenerse al día con los últimos avances en el campo médico y de la salud, fomentando la colaboración y el intercambio de buenas prácticas.', 
'Los efectos de las últimas dos intervenciones en la Universidad de Ciencias Médicas de Camagüey son notables y multidimensionales:Formación Doctoral y Desarrollo Especializado en Colaboración con Entidades Europeas y Latinoamericanas: Mejora de la Formación Académica: La colaboración con entidades europeas y latinoamericanas ha enriquecido los programas académicos, especialmente en la formación doctoral y el desarrollo especializado. Esta cooperación ha facilitado el intercambio de conocimientos y metodologías avanzadas, contribuyendo a una formación más integral y globalizada. Fortalecimiento de la Investigación: La participación en redes académicas y de investigación ha llevado a un incremento en la calidad y cantidad de proyectos investigativos, enfocados en resolver problemas de relevancia territorial y nacional. Esto sitúa a la universidad como un centro promotor de la ciencia y la innovación tecnológica.Participación en Redes Académicas y de Investigación: Reconocimiento y Diseminación del Conocimiento: La participación activa en redes académicas y de investigación ha permitido la diseminación de los resultados científicos en publicaciones y eventos nacionales e internacionales, aumentando el reconocimiento y la visibilidad de la universidad a nivel global.', 
'Estudio de Caso Cualitativo', 
'Transversal', 
'Sesgo de Accesibilidad a la Información, Sesgo de Publicación',
'Sesgo de Selección del Caso, Sesgo de Narrativa',
'CUBA',
4, 
'Movilidad');

CALL InsertarDatosArticulo('A Camacho, FG Peñalvo, AG Holgadp', 
'Construyendo el futuro de Latinoamérica: mujeres en STEM', 
2021,
'https://acofipapers.org/index.php/eiei/article/view/1847', 
'La intervención innovadora descrita en el documento se realizó en el marco del Doctorado en Ciencias de la Educación de la Universidad Pedagógica y Tecnológica de Colombia (UPTC), en colaboración con RUDECOLOMBIA. El documento describe una intervención innovadora en el ámbito de la movilidad académica y la internacionalización en la educación superior. Se caracteriza por la creación y desarrollo de redes en la integración internacional, enfocándose en la internacionalización del currículo, la flexibilidad (internas y externas con homologaciones), interdisciplinariedad, y movilidad transversal de estudiantes, profesores y directivos. También menciona el impacto de actividades internacionales transversales realizadas en pasantías presenciales y virtuales, promoviendo procesos académico-culturales, institucionales, regionales y latinoamericanos en contextos europeos y africanos. La movilidad de estudiantes y profesores es un componente clave de esta intervención, donde se resalta la importancia de la participación de diversos actores académicos y la visibilidad local, regional, nacional e internacional con bilingüismo', 
'Los efectos de esta intervención se observan en varias áreas. Primero, en la caracterización de las instituciones, sociedades científicas, grupos de investigación, y personal docente y estudiantil, enfocándose en su participación en la creación y desarrollo de redes para la integración internacional. Segundo, se nota un impacto significativo de las actividades internacionales transversales, tanto en pasantías presenciales como virtuales, que vehiculan procesos académico-culturales, institucionales, regionales y latinoamericanos con espacios europeos y africanos. Esto incluye la internacionalización del currículo, destacando la flexibilidad, interdisciplinariedad, y la movilidad transversal de estudiantes, profesores y directivos', 
'Estudio de Caso Cualitativo', 
'Transversal', 
'',
'Sesgo del Observador, Sesgo de Retrospección (Hindsight Bias), Sesgo de Accesibilidad a la Información, Sesgo de Narrativa',
'Colombia',
3, 
'Movilidad');

CALL InsertarDatosArticulo('CC Morúa, AD Bogantes', 
'De lucem aspicio a la sombra neoliberal: la tercerización de servicios de limpieza en la Universidad de Costa Rica', 
2023,
'https://www.redalyc.org/journal/729/72972345020/72972345020.pdf', 
'La intervención innovadora en movilidad académica e internacionalización se realizó principalmente en las universidades argentinas, con una mención específica a la Universidad de Buenos Aires (UBA) y su relación con el Consejo Nacional de Investigaciones Científicas y Tecnológicas (CONICET)La intervención innovadora descrita en el documento se centra en la internacionalización con una perspectiva de integración regional. Se menciona la importancia de utilizar plataformas de integración como el Mercosur y otras redes para llevar adelante respuestas coordinadas y concertadas en la educación superior, destacando valores como la solidaridad, autonomía, búsqueda de paz y desarrollo​​.Además, se señala la suspensión de las movilidades físicas debido a la pandemia, pero se enfatiza en la implementación de la movilidad virtual como una solución innovadora para mantener la internacionalización en el contexto educativo. Se menciona el registro y seguimiento de estudiantes y docentes internacionalizados y la necesidad de crear estructuras de respuesta basadas en información sistematizada​​.', 
'Los efectos de estas intervenciones incluyen la adaptación a un nuevo contexto de enseñanza y aprendizaje, donde se ha mitigado la brecha tecnológica y digital a través de la virtualización de la enseñanza. Esto ha permitido continuar con los procesos educativos y de investigación, a pesar de las restricciones físicas impuestas por la pandemia​​.La implementación de la movilidad virtual y la internacionalización solidaria en la educación superior ha llevado a repensar la evaluación como un proceso de aprendizaje y a regular la educación a distancia, tratándola como un derecho y no como un bien comercial​​.', 
'Estudio de Caso Cualitativo', 
'Transversal', 
'',
'Sesgo del Observador, Sesgo de Retrospección (Hindsight Bias), Sesgo de Accesibilidad a la Información, Sesgo de Narrativa, Sesgo de Generalización, Sesgo de Publicación',
'Argentina',
2, 
'Movilidad');

CALL InsertarDatosArticulo('JL Castro-Mero', 
'Prócticas de vinculación de estudiantes de arquitectura en tiempos de pandemia covid 19-plan de contingencia', 
2020,
'https://www.dominiodelasciencias.com/ojs/index.php/es/article/view/1434/0', 
'La intervención innovadora relacionada con la movilidad académica y la internacionalización en el contexto de la educación superior se realizó en la Universidad Autónoma de Nuevo León (UANL) en México.El documento describe una intervención innovadora centrada en la movilidad académica y la internacionalización en el contexto de la educación superior. Esta intervención se focaliza en proporcionar a los estudiantes la oportunidad de estudiar en el extranjero, introduciendo nuevas técnicas de enseñanza y facilitando el intercambio de ideas entre alumnos y profesores de distintos países. Se destaca la importancia de crear redes de conocimiento y modelos académicos que promuevan la movilidad estudiantil como un medio para la creación de nuevo conocimiento y métodos de aprendizaje. ', 
'Los efectos de esta intervención incluyen la adquisición de nuevas técnicas de aprendizaje por parte de los estudiantes, el fomento de la cooperación entre universidades y la mejora en la calidad de los estudiantes que egresan. Se menciona que las estrategias de internacionalización varían entre instituciones, pero todas comparten el objetivo de lograr la internacionalización y adaptarse a realidades y prioridades cambiantes', 
'Estudio de Caso Cualitativo', 
'Transversal', 
'Sesgo Temporal, Sesgo de Generalización',
'Sesgo de Selección del Caso, Sesgo de Accesibilidad a la Información, Sesgo de Narrativa',
'México',
2, 
'Movilidad');

CALL InsertarDatosArticulo('WMC Pérez, LFA Ferreyros', 
'Desafíos para el control de la gestión universitaria: transformación de procesos en tiempos de pandemia.', 
2022,
'http://encuentros.unermb.web.ve/index.php/encuentros/article/view/241', 
'La intervención innovadora en el ámbito de la movilidad académica y la internacionalización se lleva a cabo en la Universidad Autónoma de Nuevo León (UANL) en MéxicoEl documento describe varias intervenciones innovadoras en el ámbito de la movilidad académica y la internacionalización en la educación superior. Una de ellas se centra en la movilidad de aprendizaje para estudiantes y educadores, que busca alcanzar una educación y mentalidad global, logrando mayor cooperación internacional y posicionando a las universidades en rankings globales. Este enfoque incluye la adaptación cultural y la incorporación de prácticas basadas en las tradiciones de los países de origen de los estudiantes extranjeros, así como estrategias de financiamiento para la educación de posgrado y la mejora de infraestructura para profesores y estudiantes.', 
'Los efectos de estas intervenciones incluyen la creación de instituciones de calidad capaces de competir en el mercado internacional de la educación y la transmisión de valores de civilización de una generación a la siguiente. Se menciona también el impacto de estas estrategias en la movilidad estudiantil, reflejada en estadísticas como la proporción de estudiantes en movilidad entrante y saliente, y la influencia en la proyección internacional de las universidades.', 
'No se especifíca de forma suficiente la metodología empleada', 
'Transversal', 
'Sesgo del Observador',
'Sesgo de Narrativa, Sesgo de Generalización, Sesgo de Retrospección (Hindsight Bias)',
'México',
1, 
'Movilidad');

CALL InsertarDatosArticulo('EA Alegre Pilco, JL Dávila Ramírez', 
'Principales componentes que limitan la competitividad de las MiPymes exportadoras de la región Lima de la partida 6209.20.0000 en su etapa de internacionalización hacia el mercado de Estados Unidos, en el periodo 2016 – 2020', 
2021,
'https://repositorioacademico.upc.edu.pe/handle/10757/657782', 
'El documento describe varias intervenciones innovadoras en el ámbito de la movilidad académica y la internacionalización en la educación superior. Por ejemplo, se menciona el programa Vacances Tourisme Familles (VTF) de la Universidad de Guadalajara, que impacta en la internacionalización del currículo del Departamento de Turismo. Este programa es un caso de mejores prácticas que muestra cómo los requisitos para participar en un programa internacional de movilidad de estudiantes han creado la necesidad de mejores procesos y más apoyo para los estudiantes. Además, se discute sobre la necesidad de adaptar las estrategias de internacionalización y movilidad a las especificidades socioeconómicas y culturales de cada contexto para cumplir con la responsabilidad social y asegurar una enseñanza de calidad.', 
'Los efectos de estas intervenciones son variados. Por ejemplo, el programa VTF de la Universidad de Guadalajara ha generado cambios significativos en el proceso formativo de los estudiantes, mejorando la calidad y la relevancia de la educación. Además, ha fomentado la vinculación y cooperación con otras instituciones educativas, tanto a nivel nacional como internacional. Este programa ha logrado también una mejora en la movilidad estudiantil y en las estancias de investigación, lo que concuerda con la estrategia y visión institucional de largo plazo de la Universidad.', 
'Estudio de Caso Cualitativo', 
'Transversal', 
'',
'Sesgo de Selección del Caso, Sesgo del Observador',
'México',
1, 
'Movilidad');

CALL InsertarDatosArticulo('EA De La Torre Moreyra, SS Rodas Valverde', 
'Influencia del modelo asociativo agricultura por contrato entre los productores de palta Hass de Ica y la Corporación Frutícola de Chincha para la internacionalización de su oferta exportable durante el período 2015-2020', 
2022,
'https://repositorioacademico.upc.edu.pe/handle/10757/659945', 
'La intervención innovadora de movilidad académica y la internacionalización en educación superior, centrada en el intercambio virtual estudiantil, se lleva a cabo en las instituciones miembros del Nodo Caribe de la Red Colombiana para la Internacionalización de la Educación Superior (RCI). Las instituciones específicas mencionadas en el estudio incluyen la Corporación Politécnico de la Costa Atlántica, el Servicio Nacional de Aprendizaje [SENA], y la Corporación Universitaria del Caribe [CECAR] en Colombia. Además, se menciona la colaboración con instituciones en países como México, Argentina, y Perú, entre otros. El documento describe una intervención innovadora en el ámbito de la movilidad académica y la internacionalización en la educación superior, particularmente centrada en el intercambio virtual estudiantil. Este enfoque fue acentuado en respuesta a la pandemia de COVID-19, con el objetivo de fortalecer la estrategia de internacionalización de las instituciones educativas. Incluye actividades como pasantías de investigación virtual, prácticas empresariales, y el uso de modalidades colaborativas en línea (COIL) y clases espejo. Estas actividades tienen un impacto positivo en el perfil global de los estudiantes. Sin embargo, se menciona que la gestión docente de estas actividades es menor, y se destaca la necesidad de sensibilizar a los docentes para la continuidad de estas iniciativas', 
'Los efectos de esta intervención incluyen una tendencia hacia el desarrollo de actividades que inciden positivamente en el perfil global de los estudiantes. Se observan desafíos en la implementación, como la necesidad de sensibilización docente y la integración de estas actividades en el currículo para una adecuada evaluación y homologación. Además, se resalta la importancia del trabajo en red con otras instituciones para fortalecer la estrategia de intercambio virtual con países de diferente lengua materna', 
'Estudio No Experimental Mediante Encuesta Basado en una Muestra Representativa', 
'Transversal', 
'Sesgo de Selección de la Muestra, Sesgo de Autoselección',
'Sesgo de Cobertura, Sesgo de Deseabilidad Social, Sesgo de Fatiga',
'Colombia, México, Argentina, Perú ',
1, 
'Movilidad');

CALL InsertarDatosArticulo('R Diez Canseco Terry, L De la Fuente, A Escribano', 
'Salud, nutrición y deporte en los tiempos del COVID-19', 
2020,
'https://repositorio.usil.edu.pe/items/a3c93a57-0932-4755-b28e-04a715e610c7', 
'El documento describe varias iniciativas e intervenciones innovadoras relacionadas con la movilidad académica y la internacionalización en la educación superior y universitaria. Entre ellas se menciona la importancia de la internacionalización del currículo y la inclusión de dimensiones internacionales, interculturales o globales en la educación. Se resalta la movilidad estudiantil y las estrategias de internacionalización en casa (IeC), incluyendo programas de doble titulación, desarrollo de investigaciones conjuntas, y movilidad virtual. Además, se discute el papel activo de políticas, estrategias y prácticas educativas desde una perspectiva de internacionalización, considerando las especificidades de cada contexto socioeconómico y cultural.La intervención relacionada con la movilidad académica y la internacionalización en la educación superior se llevó a cabo en varias universidades, incluyendo: Universidad de Guadalajara (UdeG): Se menciona específicamente el desarrollo de la ciudadanía global a través de la movilidad estudiantil en el Centro Universitario de Ciencias Económico Administrativas de la UdeG. También se destaca el programa Vacances Tourisme Familles (VTF) y su impacto en la internacionalización del currículo del Departamento de Turismo de la UdeG. Universidad Veracruzana (UV): Se describe una asociación estratégica entre la Universidad Veracruzana y el University College Cork (Universidad Nacional de Irlanda en Cork, UCC) para llevar a cabo una internacionalización del currículo cruzada en ambas instituciones. Tecnológico de Antioquia-Institución Universitaria (TdeA): Se resalta el protagonismo que ha dado el TdeA a la internacionalización académica desde varios enfoques, incluyendo el campus intercultural y la internacionalización del currículo.', 
'Los efectos de estas intervenciones incluyen mejoras en el proceso formativo de los estudiantes, el desarrollo de competencias necesarias para trabajar y vivir con éxito en un contexto globalizado e interconectado, y la promoción de una mayor apreciación y tolerancia. Se menciona también el impacto limitado de la movilidad estudiantil y la necesidad de apoyar a más estudiantes en este aspecto.', 
'Estudio de Caso Cualitativo', 
'Transversal', 
'Sesgo de Generalización',
'Sesgo de Publicación, Sesgo de Accesibilidad a la Información',
'México',
1, 
'Movilidad');