CALL InsertarDatosArticulo('T Santiago', 
'Educación en tiempos de pandemia: reflexiones de alumnos y profesores sobre la enseñanza virtual universitaria en España, Italia y Ecuador', 
2020,
'https://iris.unito.it/handle/2318/1760385', 
'Formación del profesorado en TICs, con un enfoque en la enseñanza y el aprendizaje, y la adopción de modelos flexibles como respuesta a los desafíos sociales y tecnológicos. También se detallan prácticas como el uso de aula virtual, cursos MOOC, Open Course Ware (OCW), mobile learning, gamificación y realidad aumentada.', 
'Estos incluyen un aumento en las oportunidades de formación e,learning, el cambio en las dinámicas de trabajo docente y estudiantil, y un mayor énfasis en el desarrollo de competencias digitales. También se mencionan desafíos como el incremento del trabajo para los docentes debido al cambio de la presencialidad a la virtualidad y las dificultades en la gestión estratégica de las TICs.', 
'Estudio No Experimental Mediante Encuesta Basado en una Muestra Representativa', 
'Transversal', 
'',
'Sesgo de Selección , Sesgo de Medición , Sesgo de Confirmación, Sesgo del Investigador',
'Ecuador',
464, 
'TICS');

CALL InsertarDatosArticulo('C Laura', 
'Educación en tiempos de pandemia: reflexiones de alumnos y profesores sobre la enseñanza virtual universitaria en España, Italia y Ecuador', 
2020,
'https://iris.unito.it/handle/2318/1760385', 
'Formación del profesorado en TICs, con un enfoque en la enseñanza y el aprendizaje, y la adopción de modelos flexibles como respuesta a los desafíos sociales y tecnológicos. También se detallan prácticas como el uso de aula virtual, cursos MOOC, Open Course Ware (OCW), mobile learning, gamificación y realidad aumentada.', 
'Estos incluyen un aumento en las oportunidades de formación e,learning, el cambio en las dinámicas de trabajo docente y estudiantil, y un mayor énfasis en el desarrollo de competencias digitales. También se mencionan desafíos como el incremento del trabajo para los docentes debido al cambio de la presencialidad a la virtualidad y las dificultades en la gestión estratégica de las TICs.', 
'Estudio No Experimental Mediante Encuesta Basado en una Muestra Representativa', 
'Transversal', 
'',
'Sesgo de Selección , Sesgo de Medición , Sesgo de Confirmación, Sesgo del Investigador',
'Ecuador',
464, 
'TICS');

CALL InsertarDatosArticulo('T Fernanda', 
'Educación en tiempos de pandemia: reflexiones de alumnos y profesores sobre la enseñanza virtual universitaria en España, Italia y Ecuador', 
2020,
'https://iris.unito.it/handle/2318/1760385', 
'Formación del profesorado en TICs, con un enfoque en la enseñanza y el aprendizaje, y la adopción de modelos flexibles como respuesta a los desafíos sociales y tecnológicos. También se detallan prácticas como el uso de aula virtual, cursos MOOC, Open Course Ware (OCW), mobile learning, gamificación y realidad aumentada.', 
'Estos incluyen un aumento en las oportunidades de formación e,learning, el cambio en las dinámicas de trabajo docente y estudiantil, y un mayor énfasis en el desarrollo de competencias digitales. También se mencionan desafíos como el incremento del trabajo para los docentes debido al cambio de la presencialidad a la virtualidad y las dificultades en la gestión estratégica de las TICs.', 
'Estudio No Experimental Mediante Encuesta Basado en una Muestra Representativa', 
'Transversal', 
'',
'Sesgo de Selección , Sesgo de Medición , Sesgo de Confirmación, Sesgo del Investigador',
'Ecuador',
464, 
'TICS');

CALL InsertarDatosArticulo('A Parola', 
'Educación en tiempos de pandemia: reflexiones de alumnos y profesores sobre la enseñanza virtual universitaria en España, Italia y Ecuador', 
2020,
'https://iris.unito.it/handle/2318/1760385', 
'Formación del profesorado en TICs, con un enfoque en la enseñanza y el aprendizaje, y la adopción de modelos flexibles como respuesta a los desafíos sociales y tecnológicos. También se detallan prácticas como el uso de aula virtual, cursos MOOC, Open Course Ware (OCW), mobile learning, gamificación y realidad aumentada.', 
'Estos incluyen un aumento en las oportunidades de formación e,learning, el cambio en las dinámicas de trabajo docente y estudiantil, y un mayor énfasis en el desarrollo de competencias digitales. También se mencionan desafíos como el incremento del trabajo para los docentes debido al cambio de la presencialidad a la virtualidad y las dificultades en la gestión estratégica de las TICs.', 
'Estudio No Experimental Mediante Encuesta Basado en una Muestra Representativa', 
'Transversal', 
'',
'Sesgo de Selección , Sesgo de Medición , Sesgo de Confirmación, Sesgo del Investigador',
'Ecuador',
464, 
'TICS');

//Inserccion 
CALL InsertarDatosArticulo('J Martínez', 
'Competencias digitales docentes y el reto de la educación virtual derivado de la covid-19', 
2020,
'https://revistas.unisimon.edu.co/index.php/educacion/article/view/4114', 
'Implementación de un sistema de enseñanza virtual en respuesta a la pandemia de COVID,19.Esta intervención incluye el desarrollo de habilidades cognitivas y metacognitivas en estudiantes a través de acciones tutoriales, evaluación procesual y permanente, y uso de recursos tecnológicos para promover la interactividad.', 
'El documento resalta efectos como mejora en la capacidad de localizar, identificar y clasificar información digital relevante, aumento en la facilidad de colaboración y comunicación entre docentes y estudiantes, y una mayor autonomía estudiantil en el aprendizaje.', 
'Estudio No Experimental Mediante Encuesta Basado en una Muestra Representativa', 
'Transversal', 
'',
'Sesgo de Selección, Sesgo de Confirmación, Sesgo del Investigador',
'Colombia',
409, 
'TICS');

CALL InsertarDatosArticulo('MJV Ledo', 
'Innovación educativa', 
2022,
'http://ems.sld.cu/index.php/ems/article/download/3508/1385', 
'Incorporación de la gamificación y la pedagogía inversa, que consisten en utilizar juegos para motivar a los alumnos y en cambiar los roles de profesores y alumnos, respectivamente. Esto permite a los alumnos participar activamente en su propio proceso de aprendizaje y a los profesores motivar cambios educativos necesarios para la generación actual.', 
'Los efectos de estas intervenciones incluyen una experiencia de aprendizaje más positiva y motivadora para los estudiantes. La gamificación y la pedagogía inversa han llevado a un enriquecimiento del proceso de enseñanza,aprendizaje, mejorando la gestión del conocimiento a distancia y fortaleciendo la colaboración entre los actores involucrados.', 
'No se especifíca de forma suficiente la metodología empleada', 
'', 
'',
'',
'Cuba',
367, 
'TICS');

CALL InsertarDatosArticulo('EÁM Aguilera', 
'Innovación educativa', 
2022,
'http://ems.sld.cu/index.php/ems/article/download/3508/1385', 
'Incorporación de la gamificación y la pedagogía inversa, que consisten en utilizar juegos para motivar a los alumnos y en cambiar los roles de profesores y alumnos, respectivamente. Esto permite a los alumnos participar activamente en su propio proceso de aprendizaje y a los profesores motivar cambios educativos necesarios para la generación actual.', 
'Los efectos de estas intervenciones incluyen una experiencia de aprendizaje más positiva y motivadora para los estudiantes. La gamificación y la pedagogía inversa han llevado a un enriquecimiento del proceso de enseñanza,aprendizaje, mejorando la gestión del conocimiento a distancia y fortaleciendo la colaboración entre los actores involucrados.', 
'No se especifíca de forma suficiente la metodología empleada', 
'', 
'',
'',
'Cuba',
367, 
'TICS');

CALL InsertarDatosArticulo('IRM Sánchez', 
'Innovación educativa', 
2022,
'http://ems.sld.cu/index.php/ems/article/download/3508/1385', 
'Incorporación de la gamificación y la pedagogía inversa, que consisten en utilizar juegos para motivar a los alumnos y en cambiar los roles de profesores y alumnos, respectivamente. Esto permite a los alumnos participar activamente en su propio proceso de aprendizaje y a los profesores motivar cambios educativos necesarios para la generación actual.', 
'Los efectos de estas intervenciones incluyen una experiencia de aprendizaje más positiva y motivadora para los estudiantes. La gamificación y la pedagogía inversa han llevado a un enriquecimiento del proceso de enseñanza,aprendizaje, mejorando la gestión del conocimiento a distancia y fortaleciendo la colaboración entre los actores involucrados.', 
'No se especifíca de forma suficiente la metodología empleada', 
'', 
'',
'',
'Cuba',
367, 
'TICS');

CALL InsertarDatosArticulo('CH Sandoval', 
'La educación en tiempo del Covid,19 herramientas TIC: El nuevo rol Docente en el fortalecimiento del proceso enseñanza aprendizaje de las prácticas educativa', 
2020,
'https://ojs.docentes20.com/index.php/revista,docentes20/article/view/138', 
'Uso de las Tecnologías de la Información y la Comunicación (TIC) para adaptar la enseñanza al contexto de la pandemia de COVID,19. La innovación radica en la integración de herramientas TIC en el contexto virtual de las clases, lo que ha permitido a los educadores crear experiencias significativas y flexibles para los estudiantes, incluso durante el aislamiento preventivo obligatorio. Esta estrategia ha transformado el rol docente y ha redefinido los procesos pedagógicos​​.', 
'Fortalecimiento del uso de las TIC en la educación, lo que ha generado un nuevo impulso al proceso formativo. Mejora en la gestión y uso de las TIC por parte de los educadores y las directivas de las instituciones educativas. Adaptación al nuevo rol docente mediado por las TIC, lo que ha ayudado a mantener la continuidad educativa durante la pandemia​​​​.', 
'Estudio No Experimental Mediante Encuesta Basado en una Muestra No Representativa', 
'Transversal', 
'',
'Sesgo de Selección, Sesgo de Medición , Sesgo de Confirmación, Sesgo del Investigador',
'',
318, 
'TICS');

CALL InsertarDatosArticulo('GA Picón', 
'Desempeño y formación docente en competencias digitales en clases no presenciales durante la pandemia COVID,19', 
2021,
'https://dialnet.unirioja.es/servlet/articulo?codigo=8070339', 
'IntervImplementación de Nuevas Tecnologías de la Información y la Comunicación (NTIC) para facilitar la enseñanza y el aprendizaje en un entorno no presencial. Además, se menciona la capacitación y el entrenamiento de los docentes en el uso de estas tecnologías para mejorar su desempeño en la educación virtualención', 
'Los efectos de esta intervención incluyen el uso de diversas herramientas digitales y plataformas en línea para la comunicación y el desarrollo de las clases no presenciales. Se destaca el uso de mensajes de texto y redes sociales para la comunicación, así como el uso de videos y chats para el desarrollo de clases. También se observa una adaptación en las estrategias de enseñanza para replicar la experiencia de clase presencial en un entorno no presencial', 
'Estudio No Experimental Mediante Encuesta Basado en una Muestra No Representativa ', 
'Transversal', 
'',
'',
'Paraguay',
277, 
'TICS');
// Aqui ya me valio 
CALL InsertarDatosArticulo('AJP Chacín, AI González', 
'Educación superior e investigación en Latinoamérica: Transición al uso de tecnologías digitales por Covid,19', 
2020,
'https://dialnet.unirioja.es/servlet/articulo?codigo=7565470', 
'Diseño y fabricación de un ventilador mecánico por investigadores de la Pontificia Universidad Católica del Perú, llamado proyecto MASI, autorizado para su fabricación y uso por el Estado peruano. Otra iniciativa destacada es el desarrollo de dispositivos desinfectantes y de alerta para personas con discapacidades visuales y auditivas por la Universidad Nacional de Ingeniería de Perú.', 
'Los efectos de estas intervenciones incluyen la autorización estatal para la fabricación y uso del ventilador mecánico MASI, contribuyendo a la lucha contra COVID,19. Además, la creación de dispositivos desinfectantes y de alerta por la Universidad Nacional de Ingeniería ha ayudado a disminuir el contagio del virus, especialmente beneficiando a personas con discapacidades.', 
'Revisión Bibliográfica', 
'Transversal', 
'',
'Sesgo de Selección de Estudios',
'Colombia',
201, 
'TICS');

CALL InsertarDatosArticulo('DA Cueva Gaibor', 
'La tecnología educativa en tiempos de crisis', 
2020,
'http://scielo.sld.cu/scielo.php?pid=S1990,86442020000300341&script=sci_arttext', 
'La integración de las TIC en el desarrollo de nuevas prácticas educativas. El uso de tecnologías educativas para la evaluación y seguimiento del aprendizaje de los estudiantes. Fomento del trabajo autónomo, crítico, reflexivo, creativo y colaborativo de los alumnos en la construcción de conocimientos a través de las TIC.', 
'Potenciación de experiencias de aprendizaje que mejoran respecto a las prácticas tradicionales de enseñanza. Aumento en la capacidad de los estudiantes de gestionar la tecnología, los datos, la información y el conocimiento. Desarrollo de competencias tecnológicas, tanto generales como específicas, entre profesores y estudiantes.', 
'No se especifíca de forma suficiente la metodología empleada', 
'', 
'',
'',
'Ecuador',
155, 
'TICS');

CALL InsertarDatosArticulo('MP Chirinos, NAG Olivera, DC Cerra', 
'En tiempos de coronavirus: las TIC S son una buena alternativa para la educación remota', 
2020,
'https://dialnet.unirioja.es/servlet/articulo?codigo=8116140', 
'Se describe el uso de las Tecnologías de la Información y la Comunicación (TICs) en la educación remota, enfocándose especialmente en la enseñanza de lenguas extranjeras. Las intervenciones incluyen el uso de redes sociales, podcasts, videoblogs y Skype para facilitar la enseñanza y aprendizaje. Estas herramientas promueven el aprendizaje colaborativo, la comunicación y colaboración efectiva, y la transformación de los roles tradicionales de docentes y estudiantes hacia roles más dinámicos e interactivos.', 
'Mejoramiento de la comprensión lectora y auditiva. Desarrollo de habilidades en reglas gramaticales y producción escrita. Flexibilidad horaria para estudiantes y docentes. Promoción del aprendizaje colaborativo. Transformación de los roles tradicionales en educación hacia dinamismos más interactivos. Facilitación de la evaluación y retroalimentación inmediata a través de herramientas virtuales.', 
'No se especifíca de forma suficiente la metodología empleada', 
'', 
'',
'',
'Colombia',
120, 
'TICS');

CALL InsertarDatosArticulo('V Ferrada,Bustamante', 
'Formación docente en TIC y su evidencia en tiempos de COVID,19', 
2021,
'https://sintesisdejurisprudencia.uchile.cl/index.php/RSED/article/view/60715', 
'La innovación se centra en revisar y transformar las prácticas educativas a través de las TIC, especialmente en el contexto de la pandemia de COVID,19. Se menciona cómo esta situación ha llevado a una necesidad de utilizar estrategias de enseñanza adaptadas a las aulas virtuales.', 
'Por un lado, se señala que la mayoría de los docentes considera que las TIC facilitan el quehacer educativo en tiempos de confinamiento. Por otro lado, se menciona que el tipo de estrategias utilizadas en el contexto educativo a distancia puede ser percibido como menos eficaz en términos de interacción y aprendizaje, con algunos docentes y estudiantes encontrando desafíos en la adaptación a estas nuevas modalidades de enseñanza.', 
'Estudio No Experimental Mediante Encuesta Basado en una Muestra No Representativa', 
'Transversal', 
'Sesgo de Accesibilidad a la Información',
'Sesgo de Selección del Caso , Sesgo del Observador , Sesgo de Retrospección , Sesgo Temporal , Sesgo de Confirmación, Sesgo del Investigador',
'Chile',
120, 
'TICS');

CALL InsertarDatosArticulo('ÁEA Duque, AJ Argüello, BG Pineda', 
'TiCompetencias del docente en educación online en tiempo de COVID,19: Universidades Públicas de Hondurastulo', 
2020,
'https://dialnet.unirioja.es/servlet/articulo?codigo=7599941', 
'Uso de plataformas y herramientas educativas digitales, así como la transformación de métodos tradicionales a métodos virtuales para el desarrollo de clases en la Universidad Nacional Autónoma de Honduras.', 
'Un aumento significativo en el uso de tecnologías de la información y la comunicación (TIC) en el ámbito educativo. El desarrollo de competencias digitales en los docentes y su adaptación a nuevas metodologías de enseñanza y evaluación virtual. Una mejora en la interacción docente,alumno a través de plataformas virtuales, a pesar de los desafíos iniciales.', 
'Estudio No Experimental Mediante Encuesta Basado en una Muestra No Representativa', 
'Transversal', 
'',
'Sesgo de Medición , Sesgo de Confirmación, Sesgo del Investigador ',
'Honduras',
115, 
'TICS');

CALL InsertarDatosArticulo('DF Poveda,Pineda, JE Cifuentes,Medina', 
'Incorporación de las tecnologías de información y comunicación (TIC) durante el proceso de aprendizaje en la educación superior', 
2020,
'https://www.scielo.cl/scielo.php?pid=S0718,50062020000600095&script=sci_arttext', 
'Sí, se describe la intervención innovadora de incorporar las Tecnologías de la Información y Comunicación (TIC) en el proceso de aprendizaje en la educación superior. Esta intervención implica una resignificación del concepto de TIC, elevando su importancia en la construcción de diversas formas de acceder y transformar el aprendizaje, con un enfoque en el crecimiento personal y colectivo y la adquisición de nuevos saberes dentro de una disciplina.', 
'Cambios metodológicos y pedagógicos en la educación superior, favoreciendo la formación integral de los estudiantes y su capacidad para afrontar las exigencias de la sociedad del conocimiento. Mejoras en los procesos comunicacionales y de interactividad, contribuyendo a una transformación significativa de la educación superior con modalidad virtual.', 
'No se especifíca de forma suficiente la metodología empleada', 
'', 
'',
'',
'Colombia',
103, 
'TICS');

CALL InsertarDatosArticulo('JP Díaz Vera, AK Ruiz Ramírez', 
'Impacto de las TIC: desafíos y oportunidades de la Educación Superior frente al COVID,19', 
2021,
'http://scielo.senescyt.gob.ec/scielo.php?pid=S2631,27862021000200113&script=sci_arttext', 
'La intervención innovadora descrita en el documento es la transición de la modalidad presencial a virtual en la Universidad de Guayaquil, implementando las Tecnologías de la Información y Comunicación (TIC). Entre las herramientas utilizadas se mencionan Zoom, para videoconferencias y clases virtuales interactivas, y Moodle, una plataforma para la gestión y creación de espacios de aprendizaje​', 
'Incremento en la Implementación de TICs: Se observó un aumento significativo en la implementación de las TICs en las clases virtuales en comparación con el periodo pre,cuarentena. Dificultades en la Interacción y Planificación: A pesar del incremento en el uso de TICs, no se logró un proceso de enseñanza,aprendizaje óptimo debido a la falta de una buena planificación y dificultades en el uso de las plataformas, lo que afectó la interacción durante las clases sincrónicas​', 
'Estudio No Experimental Mediante Encuesta Basado en una Muestra No Representativa', 
'Transversal', 
'Sesgo de Hawthorne',
'Sesgo de Medición , Sesgo de Confirmación, Sesgo del Investigador',
'Ecuador',
102, 
'TICS');

CALL InsertarDatosArticulo('MOG Fernández', 
'La capacitación docente para una educación remota de emergencia por la pandemia de la COVID,19', 
2021,
'https://dialnet.unirioja.es/servlet/articulo?codigo=7933303', 
'Cambio temporal hacia modos alternativos de enseñanza, combinando cursos en línea, videoconferencias, uso de móviles, radio, televisión y tutoría presencial,virtual, para mantener el contacto con los estudiantes​​. Además, se utilizó el modelo TPACK para la capacitación docente, enfocándose en integrar conocimientos tecnológicos, pedagógicos y de contenido ', 
'Los efectos generados por esta intervención incluyen un aumento proporcional en las actitudes de los docentes respecto a las TIC, mejorando su aceptación y uso en la práctica docente. Se observó que la capacitación permitió a los docentes adquirir nuevas competencias digitales y comprender mejor los roles esperados de un profesor en un entorno virtual​​.', 
'Estudio No Experimental Mediante Encuesta Basado en una Muestra No Representativa', 
'Longitudinal', 
'',
'Sesgo de Selección , Sesgo de Medición , Sesgo de Confirmación,  Sesgo del Investigador',
'Mexico',
80, 
'TICS');

CALL InsertarDatosArticulo('BY Juanes Giraud, OR Munévar Mesa', 
'La virtualidad en la educación. Aspectos claves para la continuidad de la enseñanza en tiempos de pandemia', 
2020,
'http://scielo.sld.cu/scielo.php?pid=S1990,86442020000500448&script=sci_arttext', 
'"La humanidad en tiempos de pandemia". Esta intervención se llevó a cabo en una institución educativa colombiana e integró ocho áreas del conocimiento. Utilizó un Entorno Personal de Aprendizaje (PLE, por sus siglas en inglés) para acceder a información a través de distintos motores de búsqueda, gestionar tareas del proyecto con herramientas virtuales como calendarios, y fomentar el trabajo colaborativo y la comunicación entre docentes y estudiantes principalmente a través de plataformas digitales​​.', 
'Los efectos de esta intervención incluyen un destacado desempeño académico de los estudiantes, evidenciado en su participación activa en reuniones virtuales y foros. Estos foros fomentaron debates educativos que estimularon el aprendizaje, especialmente en la profundización de contenidos específicos, y ayudaron a desarrollar habilidades de pensamiento crítico, comunicación y empatía​​.', 
'Estudio de Caso Cualitativo', 
'Transversal', 
'',
'Sesgo de Selección del Caso,  Sesgo del Observador , Sesgo Temporal , Sesgo de Narrativa , Sesgo de Generalización',
'Cuba',
78, 
'TICS');

CALL InsertarDatosArticulo('A Ojeda,Beltrán, DD Ortega,Álvarez', 
'Análisis de la percepción de estudiantes presenciales acerca de clases virtuales como respuesta a la crisis del Covid,19', 
2020,
'https://revistaespacios.com/a20v41n42/a20v41n42p07.pdf', 
'Consiste en la estructuración de contenidos curriculares por parte de las instituciones de educación superior (IES) con un fuerte componente tecnológico y de innovación. El objetivo de esta intervención es permitir a los estudiantes adoptar una visión más abierta hacia la apropiación e implementación de herramientas tecnológicas y la búsqueda constante de estrategias de formación, contribuyendo así a la generación de talento humano más capaz y comprometido con la competitividad de las organizaciones​​.', 
'La investigación documenta los efectos de esta intervención. Se centra en analizar la percepción de los estudiantes sobre las clases virtuales como respuesta a la crisis del COVID,19. Los efectos descritos incluyen cambios pedagógicos introducidos, el aprendizaje de errores, la escalada de digitalización, la hibridación y el aprendizaje ubicuo. La investigación contribuye a documentar estos impactos y promover la continuación de la formación en un entorno virtual​​.', 
'Estudio No Experimental Mediante Encuesta Basado en una Muestra No Representativa', 
'Transversal', 
'',
'Sesgo de Medición , Sesgo de Confirmación, Sesgo del Investigador',
'Colombia',
68, 
'TICS');

CALL InsertarDatosArticulo('ALS Aguilar, LCP Howlet, MCG Diez', 
'Uso de las TIC como herramientas de aprendizaje. Caso de estudio: alumnos de la Facultad de Contaduría y Administración', 
2020,
'https://dialnet.unirioja.es/servlet/articulo?codigo=7625676', 
'El documento describe la implementación intensiva de plataformas de enseñanza,aprendizaje en línea como Moodle, para facilitar la creación de Entornos Virtuales de Aprendizaje (EVA), el aprendizaje colaborativo y el blended,learning​​.', 
'Los efectos de esta intervención incluyen un aumento en la disponibilidad de información y aprendizaje colaborativo. Sin embargo, también se identificaron desventajas como fallas en la conexión a Internet y distracciones durante la clase. Un hallazgo importante fue que los estudiantes mostraron buen dominio de las TIC para manejar las herramientas tecnológicas durante la contingencia sanitaria del COVID,19​​.', 
'Estudio No Experimental Mediante Encuesta Basado en una Muestra No Representativa', 
'Transversal', 
'',
'Sesgo de Selección, Sesgo de Medición , Sesgo de Confirmación, Sesgo del Investigador',
'Mexico',
65, 
'TICS');

CALL InsertarDatosArticulo('JR Guerrero Jirón, HA Vite Cevallos', 
'Uso de la tecnología de información y comunicación y las tecnologías de aprendizaje y conocimiento en tiempos de Covid,19 en la Educación Superior', 
2020,
'http://scielo.sld.cu/scielo.php?pid=S1990,86442020000600338&script=sci_arttext&tlng=pt', 
'Integración de las tecnologías de información y comunicación (TIC) y las tecnologías de aprendizaje y conocimiento (TAC) en el aula. Esta innovación incluye herramientas como aulas virtuales, chats educativos, videoconferencias y plataformas educativas en línea, facilitando así un mejor aprendizaje para los estudiantes. Estas herramientas funcionan en línea y a través de internet, permitiendo a estudiantes y maestros impartir y recibir clases desde distintos lugares, inmersos en la globalización de la educación​​.', 
'Los resultados obtenidos indican que el uso de las TIC y TAC ha permitido mitigar el impacto de la pandemia en las instituciones de educación superior. Además, se destaca la necesidad de potenciar las competencias de los docentes universitarios en el uso de estas tecnologías para mejorar el proceso de enseñanza,aprendizaje. La implementación de las TIC y TAC se ha convertido en el eje conductor para el desarrollo de las actividades académicas en las instituciones universitarias​​.', 
'No se especifíca de forma suficiente la metodología empleada', 
'', 
'',
'',
'Ecuador',
60, 
'TICS');

CALL InsertarDatosArticulo('Á Deroncele,Acosta, P Medina,Zuta', 
'Innovación educativa con TIC en universidades latinoamericanas: Estudio Multi,País.', 
2021,
'https://revistas.uam.es/reice/article/download/reice2021_19_4_009/13915/', 
'Asesorías en temas tecnológicos, acompañamiento en experiencias de innovación con TIC y la dinamización de proyectos de integración con TIC para apoyar las prácticas docentes. Además, se menciona la importancia de la capacitación y actualización permanente en metodologías innovadoras con la incorporación de TIC, así como la implementación y equipamiento de laboratorios con acceso a Internet en las instituciones universitarias​​.', 
'El estudio identifica la importancia de estas intervenciones para favorecer la apropiación de políticas TIC a nivel institucional e individual. Se destaca la necesidad de actualización en innovaciones didácticas desde las TIC, y se reconoce que la implementación de tales prácticas contribuye a la socialización y co,participación creativa de buenas prácticas pedagógicas entre docentes y estudiantes​​.', 
'Estudio No Experimental Mediante Encuesta Basado en una Muestra No Representativa', 
'Transversal', 
'',
'Sesgo de Selección, Sesgo de Medición , Sesgo de Confirmación, Sesgo del Investigador',
'Peru, Ecuador, Mexico',
58, 
'TICS');

CALL InsertarDatosArticulo('MFA Mendoza, ROG Mejía, EBA Parrales…', 
'Investigación e innovación educativa: Reto escolar por COVID,19 en el Ecuador', 
2020,
'https://dialnet.unirioja.es/servlet/articulo?codigo=8976611', 
'Implementación de entornos virtuales de aprendizaje, concebidos como medios de integración para el trabajo cooperativo. Se menciona el uso de metodologías como el aprendizaje basado en problemas y en proyectos, los cuales contribuyen a la generación de conocimientos a través de la investigación y la indagación, fomentando procesos metacognitivos en los estudiantes​​.', 
'El documento menciona la "investigación acción" como un método eficaz para asociar los problemas de diferentes tipos de grupos a través de sus propias experiencias y aportes, con el objetivo de lograr la transformación de las causas que originan problemáticas sociales. Este enfoque se orienta hacia la transformación social como resultado final de la metodología de investigación cualitativa​​.', 
'Revisión Bibliográfica', 
'Transversal', 
'',
'',
'Ecuador',
53, 
'TICS');

