CALL InsertarDatosArticulo('AD Jiménez, AG Pérez', 
'La gestión documental en función de la gobernanza De la información. El caso de la Universidad Central “Marta Abreu” de las Villas', 
2020,
'https://www.redalyc.org/journal/5727/572763612007/572763612007.pdf', 
'La intervención innovadora descrita en el documento se enfoca en los diferentes procesos y subprocesos asociados a las actividades de gestión documental. Esto incluye reglamentaciones, normativas y las diversas posturas que la institución debe asumir para el uso adecuado de su documentación para usuarios internos y externos. Se destaca el tratamiento archivístico desde el control de la creación documental hasta la difusión​​.', 
'Los efectos de esta intervención se reflejan en varios aspectos. Por ejemplo, se menciona que sólo el 38% de las preguntas relacionadas con el ítem Servicios fueron contestadas favorablemente, lo que indica un desconocimiento por parte de los archiveros sobre las potencialidades informativas de su fondo documental. Esto ha llevado a una limitación en la prestación de servicios solo a usuarios internos, característica de los sistemas institucionales de archivo en los niveles primarios dentro del ciclo de vida documental​​.', 
'Estudio No Experimental Mediante Encuesta Basado en una Muestra No Representativa', 
'Transversal', 
'Sesgo de No Respuesta, Sesgo de Fatiga',
'Sesgo de Conveniencia, Sesgo de Cobertura, Sesgo de Deseabilidad Social',
'Cuba',
16, 
'Preservacion');

CALL InsertarDatosArticulo('J Ochoa-Gutiérrez, RAS Giraldo', 
'Experiencias de gestión de los procesos de preservación digital a partir del modelo OAIS en repositorios institucionales', 
2021,
'https://revistas.um.es/analesdoc/article/view/428141', 
'En el documento se describe la implementación del modelo OAIS (Open Archival Information System) para la gestión de Repositorios Institucionales (RI). Esta intervención se caracteriza por una secuencia interrelacionada que abarca el ingreso de información, almacenamiento de publicaciones científicas, acceso a través de estándares de metadatos normalizadores y acciones de preservación digital​​', 
'Los efectos de la implementación del modelo OAIS en los RI incluyen: 1) mayor colaboración, integrando distintos repositorios mediante servicios totales o parciales y arquitectura distribuida; y 2) incremento en la seguridad y reducción de costos para instituciones con presupuestos limitados gracias al uso de arquitecturas y sistemas distribuidos​​.', 
'Revisión Sistemática', 
'Transversal', 
'Sesgo de Citación',
'Sesgo de Publicación, Sesgo de Idioma',
'Colombia, Brasil, Argentina, Perú',
3, 
'Preservacion');

CALL InsertarDatosArticulo('ADA Zitzihua, RCS Castro, IL Martínez', 
'Revisión sistemática de la literatura sobre repositorios institucionales en México: importancia de la localización referencial de metadatos', 
2022,
'https://is.uv.mx/index.php/IS/article/view/2727', 
'El documento describe una innovación relacionada con la gestión y mejora de los Repositorios Institucionales (RI) en México. La innovación propuesta implica una revisión sistemática de la literatura para evaluar el estado actual de los artículos de investigación digitales almacenados en los RI, incluyendo el Repositorio Nacional. Este enfoque se centra en extraer datos importantes para mejorar la gestión de la productividad científica y académica, destacando la importancia de la referenciación de metadatos para lograr un mayor impacto en la comunidad de usuarios y una mejor gestión de la producción científica​​.', 
'El documento no parece describir explícitamente los efectos directos de esta intervención innovadora. Sin embargo, implica que la revisión sistemática de la literatura y la mejora en la gestión de los RI, con un enfoque en la referenciación de metadatos, podrían tener un impacto positivo en la comunidad científica y académica. Esto incluiría una mejor accesibilidad y visibilidad de los artículos de investigación, así como una mejora en la gestión de la producción científica y académica​​.', 
'Revisión Sistemática', 
'Transversal', 
'Sesgo de Calidad Metodológica',
'Sesgo de Publicación, Sesgo de Idioma, Sesgo de Citación',
'México',
2, 
'Preservacion');

CALL InsertarDatosArticulo('NMA Núñez, RJR Font, LMM Hernández', 
'Repositorio de Ciencia, Tecnología e Innovación en apoyo a la gestión del desarrollo local', 
2022,
'https://dialnet.unirioja.es/servlet/articulo?codigo=8827579', 
'La intervención innovadora descrita en el documento se centra en el uso de las Tecnologías de la Información y la Comunicación (TIC) para mejorar la gestión del conocimiento y la innovación en la Universidad de Pinar del Río, Cuba. Esto incluye la implementación de repositorios institucionales para la divulgación y disponibilidad de resultados de investigación, tanto a nivel local como internacional, apoyando procesos de enseñanza, aprendizaje e investigación (página 6).', 
'Los efectos de esta intervención incluyen la creación de interrelaciones más efectivas entre el gobierno, empresas e instituciones generadoras de conocimientos, como universidades. Estas interrelaciones están orientadas a lograr soluciones y decisiones más efectivas a nivel local, aprovechando la disponibilidad de información y conocimiento sobre temas agrícolas y de producción de alimentos (página 12).', 
'Estudio de Caso Cualitativo', 
'Transversal', 
'Sesgo de Publicación',
'Sesgo del Observador, Sesgo de Accesibilidad a la Información, Sesgo de Narrativa, Sesgo de Generalización',
'Cuba',
1, 
'Preservacion');

CALL InsertarDatosArticulo('MBG Hevia, AC Villegas, AD Jiménez', 
'Fases para la Digitalización del Fondo Fotográfico Francisco de Paula Coronado de la Universidad Central “Marta Abreu” de Las Villas', 
2020,
'http://www.metodosdeinformacion.es/mei/index.php/mei/article/view/IIMEI11-N20-031058', 
'El documento describe un proceso innovador en el ámbito de la digitalización del patrimonio documental. Se detalla un proyecto para la digitalización del Fondo Fotográfico Francisco de Paula Coronado de la Universidad Central “Marta Abreu” de Las Villas. Este proceso incluye etapas como la preparación, digitalización, reconocimiento de datos, indexación, control de calidad, firma del documento, carga de datos en el archivo digital, archivo, devolución o expurgo y preservación digital​​', 
'El documento indica que el resultado del proceso de digitalización contribuirá a la normalización de este en la institución y permitirá ofrecer un servicio de mayor calidad. Esta intervención está diseñada para prevenir el deterioro de los fondos documentales y mejorar la accesibilidad y preservación de los mismos​​.', 
'Estudio No Experimental Mediante Encuesta Basado en una Muestra No Representativa', 
'Transversal', 
'Sesgo de Selección de la Muestra, Sesgo de Conveniencia, Sesgo de Cobertura',
'Sesgo de No Respuesta, Sesgo de Autoselección, Sesgo de Deseabilidad Social, Sesgo de Fatiga',
'Cuba',
1, 
'Preservacion');

CALL InsertarDatosArticulo('ME Iturralde, A Girado', 
'Reflexiones sobre la incorporación de fuentes documentales en un estudio de caso', 
2023,
'https://www.redalyc.org/journal/729/72972345015/72972345015.pdf', 
'El documento aborda una iniciativa llevada a cabo por investigadores del Núcleo de Investigación "Producciones e Investigaciones Comunicacionales y Sociales de la Ciudad Intermedia" (PROINCOMSCI) de la Facultad de Ciencias Sociales de la Universidad Nacional del Centro de la Provincia de Buenos Aires (UNCPBA). Esta iniciativa consiste en proyectos de digitalización de archivos y documentos de medios de comunicación del centro-sudeste bonaerense. Estos proyectos se enfocan en preservar y facilitar el acceso a fuentes documentales y archivos históricos locales, un aspecto crucial para el avance de investigaciones en ciencias sociales desde una perspectiva histórica​​.', 
'La intervención ha tenido varios efectos significativos. Primero, ha permitido el acceso a información que de otro modo estaría mediada por filtros institucionales o no estaría disponible públicamente. Además, ha facilitado la construcción de archivos temáticos con fines educativos, culturales y de investigación. La digitalización de estos archivos es un aporte importante para la disponibilidad pública del acervo y contribuye a la preservación de materiales originales. También destaca la importancia de socializar, compartir y difundir tanto la información como los datos rescatados, lo cual es esencial para investigaciones científicas, culturales y educativas​​​​.', 
'Estudio de Caso Cualitativo', 
'Transversal', 
'Sesgo de Accesibilidad a la Información',
'Sesgo del Observador, Sesgo de Retrospección (Hindsight Bias), Sesgo de Narrativa',
'Argentina',
1, 
'Preservacion');

CALL InsertarDatosArticulo('SM del Patrocinio Rodríguez-Palacios', 
'El autoarchivo de tesis en el RITEC como requisito de graduación para facilitar el proceso administrativo y asegurar la preservación de la memoria institucional', 
2020,
'https://cayri.uanl.mx/index.php/cp/article/view/2', 
'El documento describe una innovación implementada por el Tecnológico de Monterrey: la obligatoriedad del autoarchivo de tesis en su Repositorio Institucional Tecnológico de Monterrey (RITEC) como requisito de graduación. Esta intervención incluye la implementación de procedimientos para garantizar la eficiencia del proceso con todas sus implicaciones, como la facilitación del acceso abierto, la preservación a largo plazo de recursos, y la difusión de contenidos mediante la conexión con otros repositorios​​.', 
'Los efectos de esta intervención incluyen un mayor acceso abierto a la información científica y académica, la preservación y difusión de colecciones patrimoniales, y la maximización de la visibilidad y el impacto de la producción científica y académica en la comunidad internacional​​.El documento también destaca la eliminación de ambigüedades en los nombres de autores y la atribución correcta de las obras, lo que contribuye a la visibilidad y el reconocimiento académico​​. Se menciona la reducción de la resistencia al cambio y la aceptación de nuevas regulaciones, lo que implica un impacto positivo en la gestión administrativa y académica​​.', 
'Estudio de Caso Cualitativo', 
'Transversal', 
'',
'Sesgo del Observador, Sesgo de Retrospección (Hindsight Bias), Sesgo de Narrativa, Sesgo de Generalización',
'México',
1, 
'Preservacion');