CALL InsertarDatosArticulo('F Vallaeys', 
'Hacia una política pública latinoamericana de Responsabilidad Social Universitaria: Innovación social, calidad y pertinencia de la educación superior', 
2021,
'http://ikels-dspace.azurewebsites.net/handle/123456789/1825', 
'Se menciona la articulación entre investigación, desarrollo e innovación para el emprendimiento con fines sociales y ambientales, con énfasis en fortalecer la investigación aplicada, extensión tecnológica, emprendimiento e innovación en las instituciones de la Red Federal de Educación Profesional, Científica y Tecnológica. ', 
'Los efectos de estas intervenciones incluyen la redefinición de la calidad de la educación superior en términos de responsabilidad social por la transición ecológica, la promoción de temas de investigación definidos en consenso con grupos externos involucrados, y la transformación innovadora de la educación superior. Estas intervenciones buscan lograr un cambio en la educación superior que sea socialmente responsable, promoviendo la interdisciplinariedad, la investigación comunitaria participativa y la inclusión de temas de desarrollo sostenible y responsabilidad social en las mallas curriculares​​.', 
'No se especifica de forma suficiente la metodología empleada', 
'Transversal', 
'',
'',
'Argentina, Bolivia, Chile, Colombia, Ecuador, México, Perú',
15, 
'Sustentabilidad');

CALL InsertarDatosArticulo('P López Vela', 
'Aplicación del trabajo comunitario como estrategia de intervención para reducir los índices de contaminación ambiental en Trujillo, 2020', 
2020,
'https://repositorio.ucv.edu.pe/handle/20.500.12692/60028', 
'Programas de información sobre impactos ambientales de bienes y servicios. Estos programas permiten que los consumidores sean conscientes de las emisiones producidas por su demanda y promueven prácticas sostenibles en el sector educativo y más allá', 
'Mitigación del cambio climático y la promoción de la sostenibilidad', 
'No se especifica de forma suficiente la metodología empleada', 
'Transversal', 
'',
'',
'Colombia ',
11, 
'Sustentabilidad');

CALL InsertarDatosArticulo('NU CEPAL, UNICEF', 
'La encrucijada de la educación en América Latina y el Caribe. Informe regional de monitoreo ODS4-Educación 2030', 
2022,
'https://repositorio.cepal.org/handle/11362/48153', 
'El documento describe una intervención innovadora centrada en la educación ambiental para la sustentabilidad, enmarcada en la pedagogía crítica y el concepto de "sentipensar" de los pueblos originarios del Estado de México. Esta aproximación se basa en las bases epistémicas del buen vivir y la pedagogía crítica, proponiendo un marco alternativo para la educación ambiental sustentable​', 
'Actividades de educación ambiental sustentable accesibles a la comunidad con cuotas de bajo costo, como por ejemplo talleres con estudiantes enfocados principalmente en la promoción de huertos escolares, adaptándose a un formato virtual durante la pandemia', 
'No se especifica de forma suficiente la metodología empleada', 
'Transversal', 
'',
'',
'México',
7, 
'Sustentabilidad');

CALL InsertarDatosArticulo('K Yohannessen, M Canals, D Cáceres', 
'Reflexiones, aprendizajes y desafíos la salud ambiental en tiempos de pandemia por COVID-19', 
2020,
'https://revistaidiem.uchile.cl/index.php/RCSP/article/download/60380/63867', 
'En el documento, se describe una intervención innovadora centrada en la incorporación de la dimensión ambiental en el planeamiento curricular de la educación de pregrado y postgrado. Esta estrategia tiene como objetivo elevar la cultura ambiental de las nuevas generaciones, enfatizando la importancia de la responsabilidad educativa en la formación de ciudadanos conscientes y preparados para enfrentar los problemas ambientales. ', 
'Desarrollo de una conciencia ambiental más profunda en los estudiantes', 
'Revisión sistemática', 
'Transversal', 
'Sesgo de Accesibilidad a la Información',
'Sesgo de Confirmación, Sesgo de Idioma',
'Ecuador, Argentina, Cuba',
4, 
'Sustentabilidad');

CALL InsertarDatosArticulo('RC Flores', 
'La formación de maestros en educación ambiental. Una experiencia con base a la elaboración de situaciones problema y alternativas de solución', 
2022,
'https://www.scielo.br/j/er/a/vYFr6FLpgLx7Xs9WHQ8kfmN/', 
'El documento describe una innovadora intervención en la modernización de sistemas de educación técnica y profesional orientados al sector agroindustrial. Esta intervención involucra una inversión significativa en recursos humanos altamente calificados, integrándolos en el sector a través de sistemas de investigación y extensión.La Universidad Argentina de Empresa (UADE) se destacó en el documento por su esfuerzo en promover la innovación con un enfoque en sostenibilidad ambiental y social. La Cátedra de Biotecnología de la UADE se menciona específicamente como un ejemplo de cómo diferentes centros académicos están desplegando recursos de formación e investigación en temas de innovación. Esto implica que la UADE está tomando medidas activas para anticiparse al conocimiento y habilidades requeridos en sectores específicos, como el agroindustrial, a través de su programa de Biotecnología.', 
'Esto implica que la UADE está tomando medidas activas para anticiparse al conocimiento y habilidades requeridos en sectores específicos, como el agroindustrial, a través de su programa de Biotecnología.', 
'No se especifica de forma suficiente la metodología empleada', 
'Transversal', 
'',
'',
'Argentina, Brasil, Uruguay',
2, 
'Sustentabilidad');

CALL InsertarDatosArticulo('ARR Naupa', 
'La gestión pública y desarrollo sostenible en las entidades del sector educación', 
2022,
'https://dilemascontemporaneoseducacionpoliticayvalores.com/index.php/dilemas/article/view/3401', 
'El documento describe una experiencia de formación de maestros en educación ambiental centrada en el desarrollo de habilidades de pensamiento crítico. Esta experiencia se basa en la elaboración de situaciones problema y alternativas de solución, donde los futuros maestros identifican y analizan problemas relacionados con su comunidad o eventos en su contexto para construir diversas soluciones. Se destaca que la construcción de situaciones problema es una herramienta pedagógica efectiva para desarrollar el pensamiento crítico, fomentando la reflexión y el análisis de las causas de los problemas ambientales y la búsqueda de prácticas educativas para la adaptación, mitigación o resiliencia frente a estos problemas​', 
'Los resultados de la experiencia mostraron que la construcción de situaciones problema es una alternativa viable para el desarrollo de habilidades de pensamiento crítico.', 
'Estudio de Caso Cualitativo', 
'Transversal', 
'Sesgo de Accesibilidad a la Información, Sesgo del Observador',
'Sesgo de Selección del Caso, Sesgo de Narrativa, Sesgo de Generalización',
'México',
10, 
'Sustentabilidad');

CALL InsertarDatosArticulo('RRV Rodríguez', 
'Ante una pandemia global existen oportunidades para una producción y consumo responsable en el Perú', 
2021,
'https://revistas.uroosevelt.edu.pe/index.php/VISCT/article/view/80', 
'El programa "Creación de Empresas Asociativas de base universitaria" implementado por la UNED utiliza herramientas de cooperativismo, economía social, solidarismo, asociatividad y desarrollo sostenible. Estos enfoques sirven como ejes transversales para el emprendimiento asociativo sostenible, enfocándose en el empoderamiento territorial en zonas vulnerables de Costa Rica. Se integran acciones de capacitación en Educación para el Desarrollo Sostenible (EDS), contemplando planes de estudio que incluyen temas como cambio climático, reducción del riesgo de desastres, y consumo y producción sostenibles​', 
'Los efectos de esta intervención incluyen la trazabilidad del impacto territorial en un plazo no menor a cinco años en desarrollo sostenible, mediante el seguimiento de los indicadores del Índice de Progreso Social (IPS) Cantonal. Se busca gestionar alianzas estratégicas con distintos actores territoriales para influir en el desarrollo político-social y económico del país, vinculando estas acciones al cumplimiento de los 17 Objetivos de Desarrollo Sostenible (ODS)', 
'Estudio de Caso Cualitativo', 
'Transversal', 
'Sesgo del Observador',
'Sesgo de Generalización, Sesgo de Publicación, Sesgo de Narrativa',
'Costa Rica',
1, 
'Sustentabilidad');