CALL InsertarDatosArticulo('M Díaz-Canel-Bermúdez, JL García-Cuevas', 
'Educación superior, innovación y gestión de gobierno para el desarrollo 2012-2020', 
2020,
'http://scielo.sld.cu/scielo.php?pid=S1815-59362020000300008&script=sci_arttext', 
'Esta intervención implica el fortalecimiento de entidades y colectivos vinculados al desarrollo y la Ciencia, Tecnología e Innovación (CTI) por parte de la educación superior. Se menciona la importancia de que los directivos y especialistas implicados obtengan maestrías o doctorados en temas relacionados con sus proyectos de Investigación y Desarrollo (I+D) o innovación, preferiblemente con cotutoría, para contribuir al desarrollo y la CTI​​.', 
'Los efectos generados por esta intervención incluyen un mayor impacto en innovación y ciencia, reflejado en la obtención de conocimientos, maestrías y doctorados a partir de innovaciones pertinentes de base científica. Se enfatiza que para lograr una efectiva vinculación entre la universidad y el sector productivo, la colaboración debe basarse en un código ético sólido y en una perspectiva de beneficio mutuo​​.', 
'Estudio de caso cualitativo', 
'Transversal', 
'',
'Sesgo de Selección del Caso, Sesgo del Observador, Sesgo de Accesibilidad a la Información, Sesgo Temporal, Sesgo de Narrativa',
'CUBA',
37, 
'Trasmision');

CALL InsertarDatosArticulo('M Dini, N Gligo, A Patiño', 
'Transformación digital de las mipymes: elementos para el diseño de políticas', 
2021,
'https://repositorio.cepal.org/handle/11362/47183', 
'formación y consolidación de competencias digitales a través de cursos y programas de capacitación, y la generación de bienes colectivos como plantas o laboratorios demostrativos para la gestión eficiente de tecnologías con altas economías de escala.', 
'Los efectos generados por estas intervenciones incluyen la mejora en la eficiencia de los procesos, el ahorro de costos, mejoras en la relación con los clientes, desarrollo de nuevos productos, y nuevos modelos de negocios. Estos beneficios están vinculados con la diferenciación de productos, búsqueda de liderazgo empresarial, acceso a nuevos mercados, fidelización con clientes y reducción de costos.', 
'Revisión sistemática ', 
'Transversal', 
'',
'Sesgo de Idioma, Sesgo de Selección de Estudios, Sesgo de Confirmación, Sesgo de Heterogeneidad',
'Brasil,Chile,Ecuador,México ',
34, 
'Trasmision');

CALL InsertarDatosArticulo('AG Rodríguez, RH Aramendis, A Deana, R García', 
'El aporte de la biotecnología médica frente a la pandemia de COVID-19 y lecciones para su desarrollo mediante las estrategias nacionales de bioeconomía: estudios de caso de Colombia, Costa Rica y el Uruguay', 
2020,
'https://repository.eclac.org/handle/11362/46533', 
'La colaboración entre universidades y empresas para la transferencia tecnológica en el campo de la biotecnología médica y biomédica. Se menciona la generación de vínculos de colaboración entre grupos de investigación y la integración entre tecnologías de la Cuarta Revolución Industrial y las ciencias de la vida', 
'Participación del sector privado en actividades de I+D+i y  cambios en el modelo estatal de asignación de recursos y en los procesos regulatorios, además de modificar la percepción pública sobre la ciencia y la tecnología', 
'Estudios de caso cualitativo', 
'Transversal', 
'Sesgo de Generalización',
'Sesgo de Selección del Caso, Sesgo de Retrospección (Hindsight Bias), Sesgo de Accesibilidad a la Información, Sesgo de Narrativa',
'Colombia, Costa Rica, Uruguay',
9, 
'Trasmision');

CALL InsertarDatosArticulo('T Bartels Ortega', 
'El rol de la Agencia Universitaria para la Gestión del Emprendimiento (AUGE) en la innovación e internacionalización de las micro, pequeñas y medianas empresas (Mipymes). País: Costa Rica', 
2021,
'https://repositorio.uchile.cl/bitstream/handle/2250/184282/El_rol_de_la_Agencia_Universitaria_para_la_Gestion_del_Emprendimiento_(AUGE)_en_la_innovacion_e_internacionalizacion_de_las_micro,_pequenas_y_medianas_empresas_(Mipymes)._Pais_Costa_Rica.pdf?sequence=1', 
'Se destaca la importancia del aprendizaje interactivo y el acercamiento entre la academia y el sector empresarial, con énfasis en la generación de nuevos conocimientos a través de procesos de investigación y desarrollo. La Universidad de Costa Rica (UCR) juega un papel estratégico en este ecosistema, promoviendo la difusión de conocimiento y la incorporación de componentes innovadores en los negocios. Se mencionan acciones específicas como la formación especializada y el establecimiento de relaciones institucionales para promover la innovación en las micro, pequeñas y medianas empresas (mipymes)​​​​​​​​​​​​.', 
'Los efectos generados por esta intervención incluyen el fortalecimiento de las capacidades de innovación de las empresas a través de la interacción y colaboración entre empresas locales y multinacionales. También se menciona la mejora en el proceso de aprendizaje de las mipymes, el acceso a mecanismos educativos sofisticados y la formación especializada que fomenta la incorporación de elementos innovadores en los negocios. Estos efectos contribuyen al desarrollo empresarial desde la investigación básica y la divulgación científica, así como al incremento de la capacidad de innovación y el entendimiento de la innovación como parte de la cultura empresarial​​​​.', 
'Estudio de caso cualitativo', 
'Transversal', 
'',
'Sesgo del Observador, Sesgo de Retrospección, Sesgo de Narrativa, Sesgo de Generalización, Sesgo de Publicación',
'Costa Rica',
2, 
'Trasmision');

CALL InsertarDatosArticulo('JA Campos Arrieta', 
'Elaboración de una guía de buenas prácticas en Gestión de la Innovación Tecnológica para empresas del sector de las TICs colombiano', 
2022,
'https://repositorio.uniandes.edu.co/handle/1992/58805', 
'Se trata de una "Guía de Buenas Prácticas en Gestión de la Innovación Tecnológica (GITE) para el sector TICs colombiano". Esta guía incluye un compendio de información sobre innovación y gestión de la innovación tecnológica. La metodología empleada para desarrollar la guía incluyó sesiones de trabajo con empresas, utilizando herramientas y contenidos que ayudaron a los participantes a ubicarse en el contexto de la innovación, identificar capacidades y factores clave para desarrollar una estrategia de innovación efectiva', 
'Los efectos generados por esta intervención incluyen un mejor entendimiento y familiarización de los participantes con el contexto de innovación y gestión de la innovación. Se menciona el desarrollo de un proceso de aplicación práctica de las herramientas en la realidad empresarial, lo que llevó a conclusiones, propuestas e iniciativas surgidas de la interacción entre los participantes', 
'No se especifica de forma suficiente la metodología empleada', 
'No se especifíca la temporalidad', 
'',
'',
'Colombia',
1, 
'Trasmision');

CALL InsertarDatosArticulo('A Deana, L Pittaluga', 
'Desarrollo del clúster de biotecnología médica en Uruguay tras la pandemia generada por la COVID-19', 
2020,
'https://citinde.ei.udelar.edu.uy/uploads/bibliografia/6b574e93576a2bc3435c1a80b9e811961f1328fd.pdf', 
'Se detalla la creación de Spin-offs Universitarios o USOs (University Spin-Offs), que han emergido como un mecanismo importante para la explotación y transferencia del conocimiento científico generado por instituciones académicas. Las universidades, especialmente a través de la creación de USOs, se han convertido en actores clave en las agendas de emprendimiento regional debido a sus actividades de transferencia de tecnología. El modelo Spin-Off Social Planificado (SOSP) se utiliza para el territorio, basándose en los fundamentos del cooperativismo y la administración, inspirándose en los principios del Spin-Off, aunque no en empresas universitarias de alto nivel tecnológico, sino en un nivel social planificado y de economía primaria y secundaria. Este modelo incluye la creación de cooperativas de base universitaria que vinculan a estudiantes y graduados con comunidades, utilizando tecnologías de comunicación y aprovechando tecnologías disruptivas para el desarrollo de proyectos cooperativos', 
'La implementación de este modelo ha llevado al desarrollo de diversas políticas públicas y universitarias para fomentar la creación y crecimiento de USOs. Se observan efectos como el fortalecimiento del tejido social en las comunidades, la creación de oportunidades de empleo directas e indirectas en los territorios, y el desarrollo de capacidades personales, sociales, ambientales y económicas. También se menciona el impacto positivo en el lanzamiento de USOs y la influencia del contexto regional en el desempeño de estas empresas', 
'No se especifica de forma suficiente la metodología empleada', 
'No se especifíca la temporalidad', 
'',
'',
'Costa Rica',
1, 
'Trasmision');

CALL InsertarDatosArticulo('BM Villanueva, JC Michalus', 
'Vinculación colaborativa en tiempos de aislamiento social', 
2020,
'http://www3.fi.mdp.edu.ar/otec/revista/index.php/AACINI-RIII/article/view/19', 
'La intervención incluyó una colaboración entre instituciones académicas, como la Universidad Nacional de Salta y la Universidad Nacional de Misiones, y entidades empresariales como la Unión Industrial de Salta (UIS) y el Programa de Apoyo Profesional a Pequeños Emprendimientos Salteños (APPES). Esta colaboración fomenta un flujo bidireccional de conocimientos, donde las universidades pueden transferir hallazgos de investigación y conocimientos técnicos a las empresas, y viceversa.', 
'La creación de mapas geo-referenciales y el uso de herramientas como R-Studio para analizar datos de empresas son ejemplos de cómo se puede transferir conocimiento técnico y analítico a las empresas. Esto les proporciona recursos valiosos para entender mejor su distribución geográfica y posiblemente identificar oportunidades de negocio o áreas para la expansión.', 
'Estudio No Experimental Mediante Encuesta Basado en una Muestra No Representativa', 
'Transversal', 
'Sesgo de Conveniencia',
'Sesgo de No Respuesta, Sesgo de Autoselección, Sesgo de Cobertura, Sesgo de Recordatorio',
'Argentina',
1, 
'Trasmision');

CALL InsertarDatosArticulo('AO Mejía Chávez, JL Solleiro Rebolledo', 
'Distribución regional de empresas innovadoras: el caso de las ganadoras del Premio Nacional de Tecnología e Innovación (PNTi)', 
2021,
'http://ru.iiec.unam.mx/5594/', 
'Se destacan iniciativas como el diseño y promoción de programas de formación, capacitación, asistencia técnica y asesoría especializada, que buscan fomentar la formalización y generación empresarial, del empleo y el teletrabajo. Además, se enfatiza en fortalecer las relaciones entre Universidad - Empresa - Estado para trabajar conjuntamente en el desarrollo innovador en sus regiones. Leyes como la Ley 29 de 1990 y la Ley 1286 de 2009 respaldan estas iniciativas, promoviendo la investigación científica y el desarrollo tecnológico en Colombia ', 
'Los efectos de estas intervenciones incluyen la contribución a la transformación digital del país, reducción de costos fijos en las empresas, aumento en la productividad, mejora en la calidad de vida de los trabajadores, inclusión social, aporte al mejoramiento de la movilidad en las ciudades, reducción de índices de contaminación, impulso al uso y apropiación de nuevas tecnologías y contribución a ciudades más sostenibles', 
'Estudio No Experimental Mediante Encuesta Basado en una Muestra Representativa', 
'Transversal', 
'Sesgo de No Respuesta',
'Sesgo de Selección de la muestra, Sesgo de Cobertura',
'Colombia',
1, 
'Trasmision');

CALL InsertarDatosArticulo('E Olmos, L Wainer', 
'Economía circular: el caso de Uruguay, logros, desafíos y lecciones aprendidas.', 
2021,
'https://www.colibri.udelar.edu.uy/jspui/handle/20.500.12008/34863', 
'Esta intervención se realiza mediante un modelo didáctico desarrollado por el Departamento de Estudios a Distancia de la Universidad Autónoma de Manizales (DEAD UAM) para sus prácticas profesionales. Incluye la colaboración entre empresas y universidades a través de un centro de orientación de empleo o centros especializados en ubicación laboral, particularmente para personas con discapacidad. Las prácticas desarrolladas por la UNED se presentan como un formato ideal para articular empresas, universidades y estudiantes, fomentando la vinculación a proyectos concretos y la resolución de problemas preestablecidos utilizando TIC y construyendo ecosistemas innovadores', 
'Los efectos generados por esta intervención incluyen la creación de escenarios de cocreación y construcción, y la utilización de tutorías telefónicas, por televisión, virtuales o por redes sociales. Se emplearon técnicas cuantitativas para evaluar los resultados, revisando registros en la plataforma Moodle y datos de encuestas de percepción y talleres para el estudiantado. Estos esfuerzos se centraron en conocer las actitudes del estudiantado en torno a la implementación del Modelo de Entornos Convergentes a través de diferentes componentes de la Secuencia Didáctica Digital', 
'Estudio No Experimental Mediante Encuesta Basado en una Muestra Representativa', 
'Transversal', 
'Sesgo de Autoselección, Sesgo de Conveniencia',
'Sesgo de Cobertura, Sesgo de No Respuesta, Sesgo de Autoselección, Sesgo de Cobertura',
'Colombia',
1, 
'Trasmision');

CALL InsertarDatosArticulo('EA Alegre Pilco, JL Dávila Ramírez', 
'Principales componentes que limitan la competitividad de las MiPymes exportadoras de la región Lima de la partida 6209.20.0000 en su etapa de internacionalización hacia el mercado de Estados Unidos, en el periodo 2016 – 2020', 
2021,
'https://repositorioacademico.upc.edu.pe/handle/10757/657782', 
'Se enfoca en el desarrollo de capacidades de innovación en PYMES, especialmente en el Valle de Aburrá, Colombia. Esta intervención incluye la creación, absorción, integración y reconfiguración de conocimiento, considerados procesos clave para fomentar la innovación. Se destaca la importancia de la capacitación formal e informal, la colaboración entre unidades funcionales y organizaciones, y la gestión del conocimiento como elementos cruciales para impulsar la capacidad innovadora de las organizaciones', 
'Los efectos generados por esta intervención incluyen un aumento en la capacidad de innovación de las PYMES. Se observa que las empresas con un enfoque más fuerte en la absorción y aplicación del conocimiento, especialmente aquellas con procesos bien establecidos de creación y gestión de conocimientos, tienden a concebir ideas innovadoras que se materializan en mejoras operativas y estratégicas. Se resalta que las PYMES con capacidades de innovación avanzadas fueron menos afectadas por crisis como la pandemia de COVID-19, adaptándose mejor a las nuevas circunstancias y manteniendo la competitividad', 
'Estudio de caso cualitativo', 
'No se especifíca la temporalidad', 
'Sesgo del Observador',
'Sesgo de Selección del Caso, Sesgo de Retrospección, Sesgo de Narrativa, Sesgo de Generalización',
'Colombia',
1, 
'Trasmision');

CALL InsertarDatosArticulo('J Reyes Hernández, A Bustio Ramos', 
'Estrategia de educación ambiental, con enfoque de organización que aprende, en una empresa pesquera industrial', 
2022,
'http://scielo.sld.cu/scielo.php?pid=S2218-36202022000200388&script=sci_arttext', 
'Se presenta la experiencia de integrar el curso "EIF-439O Uso Estratégico del Comercio Electrónico" en la Universidad Nacional de Costa Rica con el proyecto UNAPROPYMES. Este proyecto fue creado para apoyar a las pequeñas y medianas empresas (PyMEs) de Costa Rica durante la pandemia de COVID-19. Se modificó el curso para incluir casos reales y desarrollar prototipos de comercio electrónico, aplicando pensamiento de diseño y experiencia de usuario (UX), y se abrió a estudiantes de otras disciplinas.', 
'Los efectos de esta intervención incluyen la oportunidad para los estudiantes de aplicar conocimientos reales en comercio electrónico, desarrollar habilidades blandas trabajando en equipos multidisciplinarios y interactuar con PyMEs. Además, contribuyeron al desarrollo de prototipos de comercio electrónico para las empresas participantes, apoyando así a la recuperación económica y social del país.', 
'No se especifica de forma suficiente la metodología empleada', 
'Transversal', 
'',
'',
'Costa Rica',
1, 
'Trasmision');

