CALL InsertarDatosArticulo('EP Alvarez-Flores', 
'Uso crítico y seguro de tecnologías digitales de profesores universitarios', 
2021,
'https://www.scielo.cl/scielo.php?pid=S0718-50062021000100033&script=sci_arttext', 
'El documento describe una intervención centrada en la capacitación y el uso crítico y seguro de tecnologías digitales por parte de profesores universitarios. Se enfoca en el desarrollo de competencias digitales, incluyendo la formación en seguridad digital, para asegurar que los profesores estén equipados para navegar y utilizar Internet de manera segura y responsable, conscientes de sus responsabilidades y riesgos como ciudadanos digitales. La intervención es innovadora en el sentido de que aborda un elemento digital poco explorado en las capacitaciones tradicionales, apuntando a mejorar el bienestar físico, psicológico y social de los docentes al utilizar tecnologías digitales.', 
'Los efectos de la intervención incluyen una mejora en los hábitos de protección y un aumento en el nivel competencial de los profesores en relación con el uso seguro y responsable de tecnologías digitales. Se observó que los sujetos con capacitación previa en seguridad digital mostraron mejores prácticas de protección y un mayor nivel de competencia en comparación con aquellos que no habían recibido tal formación. Esto sugiere que la intervención fue eficaz en reforzar el uso responsable de las tecnologías y en prevenir comportamientos de riesgo en entornos digitales.', 
'Estudio No Experimental Mediante Encuesta Basado en una Muestra No Representativa', 
'Transversal', 
'Sesgo de Selección de la Muestra, Sesgo de Autoselección, Sesgo de Conveniencia',
'Sesgo de No Respuesta, Sesgo de Cobertura, Sesgo de Deseabilidad Social, Sesgo de Recordatorio',
'Argentina, Chile, Colombia, Ecuador, El Salvador, México, Perú, Venezuela',
31, 
'Ciberseguridad');

CALL InsertarDatosArticulo('A Bogantes', 
'El rol de la seguridad informática en el ámbito académico y los sistemas de información asociados', 
2020,
'https://www.iiisci.org/journal/PDV/risci/pdfs/CB294NT20.pdf', 
'El documento describe un programa de capacitación y concientización enfocado en la seguridad informática y la prevención de delitos informáticos en Costa Rica. Este programa está dirigido a la comunidad estudiantil del programa de Ingeniería Informática de la Universidad Estatal a Distancia (UNED) y tiene como objetivo aplicar buenas prácticas tecnológicas y brindar apoyo en materia de seguridad informática. La intervención incluye formación sobre buenas prácticas en seguridad informática, divulgación de conocimientos y creación de conciencia sobre el uso seguro y responsable del internet y nuevas tecnologías.', 
'La intervención busca minimizar el impacto de la reincidencia de los delitos informáticos en Costa Rica. Se pretende desarrollar habilidades necesarias para enfrentar los desafíos de la Cuarta Revolución Industrial, promover el conocimiento sobre buenas prácticas en sistemas de información y dispositivos electrónicos, y fomentar la aplicación de técnicas de ciberseguridad. Este programa se enfoca en la prevención de delitos informáticos mediante la capacitación y concientización en el ámbito académico.', 
'Revisión Bibliográfica', 
'Transversal', 
'',
'',
'Costa Rica',
6, 
'Ciberseguridad');

CALL InsertarDatosArticulo('JJ Castro-Maldonado, HF Villar-Vega', 
'Análisis de riesgos y vulnerabilidades de seguridad informática aplicando técnicas de inteligencia artificial orientado a instituciones de educación superior', 
2021,
'http://revistas.sena.edu.co/index.php/Re_Mo/article/download/4543/4734', 
'El documento describe una intervención innovadora en el campo de la seguridad informática aplicando técnicas de inteligencia artificial (IA) en instituciones de educación superior. Esta intervención se centra en la identificación, desarrollo y aplicación de tecnologías que contribuyan a fortalecer los sistemas de prevención de ataques informáticos por ciberdelincuentes. Se menciona el desarrollo de árboles de decisión para modelar el comportamiento de incidentes, destacando la importancia de la capacitación continua y la implementación de políticas orientadas al fortalecimiento de competencias en personas involucradas en ciberseguridad', 
'Los efectos de esta intervención incluyen el fortalecimiento de las competencias de los estudiantes y miembros de la comunidad académica en temas relacionados con la prevención de ciberataques y delitos informáticos. Se señala un aumento en la implementación de técnicas de IA dentro de la seguridad informática, lo cual es eficaz para obtener modelos que identifican vulnerabilidades o riesgos informáticos. Esto permite mitigar los impactos de los ciberataques.', 
'Revisión Bibliográfica', 
'Transversal', 
'',
'',
'México',
4, 
'Ciberseguridad');

CALL InsertarDatosArticulo('JIM Secaira, RD Ocampo, ERZ Mera', 
'El sistema de gestión de seguridad de la información bajo la norma NTE ISO/IEC 27001 en instituciones de Educación Superior (Ecuador).(Original)', 
2020,
'https://dialnet.unirioja.es/servlet/articulo?codigo=7414351', 
'Se describe una intervención innovadora que se enfoca en el desarrollo y aplicación de un Sistema de Gestión de Seguridad de la Información (SGSI) para instituciones de educación superior en Ecuador, bajo la norma NTE INEN-ISO/IEC 27001. Esta metodología propuesta facilita el desarrollo de las fases del ciclo PHVA (Planear, Hacer, Verificar y Actuar) a nivel institucional, con un enfoque en mejorar la seguridad de la información en las universidades​​.', 
'La documentación no proporciona una descripción detallada de los efectos específicos generados por la intervención del SGSI. Sin embargo, se menciona que la implementación del SGSI está orientada hacia la mejora continua, la recuperación de procesos críticos, la integración de la seguridad de la información en los sistemas de gestión de la continuidad del negocio, y la mejora de los niveles de confidencialidad, integridad y disponibilidad de la información​​.', 
'Estudio de Caso Cualitativo', 
'Transversal', 
'Sesgo de Generalización',
'Sesgo de Selección del Caso, Sesgo del Observador, Sesgo de Narrativa',
'Ecuador',
4, 
'Ciberseguridad');

CALL InsertarDatosArticulo('PI Morales-Paredes, RPM Chicaiza', 
'Ciberseguridad en plataformas educativas institucionales de educación superior de la provincia de Tungurahua-Ecuador', 
2021,
'https://dialnet.unirioja.es/servlet/articulo?codigo=8091394', 
'En el documento se describe una intervención innovadora centrada en el registro de vulnerabilidades identificadas en pruebas de penetración y la generación de recomendaciones o salvaguardas. Esto está dirigido a proteger contra ataques externos que podrían afectar la autenticación, disponibilidad, integridad y confidencialidad (página 17)', 
'Los efectos de la intervención incluyen el desarrollo de procedimientos para prepararse para ataques cibernéticos continuos y futuros. Se destaca la falta de estudios con procedimientos para mitigar los riesgos de ciberseguridad en aplicaciones web o entornos educativos. Además, se mencionan las amenazas comunes en aplicaciones web y cómo afectan las etapas de seguridad como autenticación, comunicación insegura, disponibilidad, confidencialidad, manejo incorrecto de errores e integridad (página 9, 16, 11).', 
'Revisión Bibliográfica', 
'Transversal', 
'',
'',
'Ecuador',
2, 
'Ciberseguridad');

CALL InsertarDatosArticulo('PAP Garcia, DA Pesantez', 
'Análisis de ciberseguridad en plataformas e-learning: Revisión sistemática de la literatura', 
2023,
'http://45.184.102.148:8081/index.php/RCP_ESPOCH/article/view/179', 
'El documento describe varias intervenciones innovadoras en el ámbito de la ciberseguridad para plataformas e-learning. Entre ellas, se menciona la implementación de la protección de red Azure DDOS y la limitación de las solicitudes de los clientes desde los mismos puntos de conexión, subredes y entidades federadas. Además, se resalta la importancia de implementar un sistema de prevención y detección de intrusos (IDS/IPS) para monitorear las conexiones y alertar sobre intentos de acceso no permitidos. Se sugiere también el uso de dispositivos con funcionalidad mixta que incluyan antivirus, antispam, antispyware y otros, como un equipo de gestión de amenazas unificadas (UTM), para manejar de manera integrada las ciberamenazas​​.', 
'El documento aborda los efectos de las intervenciones en términos de gestión de riesgos y mitigación de amenazas en plataformas e-learning. Se destaca la identificación y valoración de riesgos, clasificándolos en diferentes zonas según su probabilidad e impacto. Se argumenta que las investigaciones en ciberseguridad en plataformas e-learning buscan implementar medidas de seguridad y métodos adecuados basados en la protección de datos y seguridad de la información. Las vulnerabilidades más destacadas incluyen la Denegación de servicio (DoS), Inyección SQL, División de respuesta HTTP y secuencias de comandos en sitios cruzados (XSS), que son principales problemas para las plataformas, provocando sabotajes en los servicios o situaciones peligrosas​​.', 
'Revisión Sistemática', 
'Transversal', 
'Sesgo de idioma',
'Sesgo de calidad metodológica, Sesgo de heterogeneidad',
'Ecuador',
1, 
'Ciberseguridad');