CALL InsertarDatosArticulo('B Pastora Alejo', 
'La planificación de estrategias de enseñanza en un entorno virtual de aprendizaje', 
2021,
'http://scielo.senescyt.gob.ec/scielo.php?script=sci_arttext&pid=S2631-27862021000300059', 
'El documento describe una intervención innovadora en la planificación de estrategias de enseñanza en un Entorno Virtual de Aprendizaje (EVA). Esta intervención se concentra en adaptar la educación a la era digital, utilizando Tecnologías de la Información y Comunicación (TIC) para desarrollar pensamiento computacional y de resolución de problemas en los estudiantes, así como fomentar una postura autocritica y critica frente a la realidad social. Se destacan estrategias que facilitan el aprendizaje autónomo y el trabajo colaborativo utilizando herramientas tecnológicas y multimedia​​.', 
'Los efectos de esta intervención incluyen una mejora en la calidad y variedad de la enseñanza-aprendizaje, que no se alcanzaría con métodos convencionales. Se facilita la creatividad, la flexibilidad de pensamiento para resolver problemas, amplía la imaginación y curiosidad de los estudiantes. Además, se promueve el aprendizaje individual y colaborativo, potenciando habilidades como el pensamiento computacional y crítico-reflexivo, y la participación activa en procesos de resolución de problemas​​.', 
'Estudio No Experimental Mediante Encuesta Basado en una Muestra No Representativa', 
'Transversal', 
'',
'Sesgo de Selección de la Muestra, Sesgo de Conveniencia, Sesgo de Cobertura',
'Ecuador',
74, 
'Software');

CALL InsertarDatosArticulo('JI Robaina-Castillo, F Hernández-García', 
'Aplicación multimedia para el estudio de la medicina natural y tradicional integrada a la pediatría', 
2020,
'https://www.sciencedirect.com/science/article/pii/S1575181318301402', 
'El documento describe una intervención innovadora en forma de una aplicación multimedia para el estudio de la medicina natural y tradicional integrada a la pediatría. Esta aplicación, denominada "NatuPedia", se presenta como un recurso necesario con potencial para ser aplicado durante clases, tiempos lectivos, talleres y otras actividades curriculares. Está diseñada para generalizarse en la docencia de pregrado y como material de estudio complementario en las residencias de especialidades de Pediatría y Medicina Natural y Tradicional (MNT)​​', 
'La utilización de "NatuPedia" resultó en mejoras significativas en el aprendizaje de los estudiantes. Más del 60% de los estudiantes lograron responder correctamente las preguntas de un test después de usar el producto, evidenciando una mejor comprensión y adquisición de conocimientos relacionados con la medicina natural y tradicional en pediatría​​.', 
'Estudio Cuasi-Experimental', 
'Transversal', 
'',
'Sesgo de Hawthorne, Sesgo de Medición, Sesgo de Confirmación/Sesgo del Investigador',
'Cuba',
56, 
'Software');

CALL InsertarDatosArticulo('J Viamontes Beltrán, RD Morales Basulto', 
'Endosoft: herramienta para el aprendizaje de las patologías pulpares y periapicales', 
2020,
'http://scielo.sld.cu/scielo.php?pid=S1729-519X2020000500014&script=sci_arttext&tlng=en', 
'El documento describe el desarrollo de un software educativo llamado "Endosoft", diseñado para el aprendizaje de las patologías pulpares y periapicales en estudiantes de Estomatología. Este software es un producto terminado digital que incorpora textos, imágenes, videos y ejercicios de autoevaluación. Se emplearon métodos histórico-lógico, analítico-sintético y sistémico-estructural para su desarrollo, junto con una revisión documental y encuestas para evaluar su efectividad​​​​​​.', 
'El "Endosoft" fue evaluado mediante criterios de expertos y usuarios, con énfasis en la calidad técnica del software, la calidad del contenido, su funcionalidad, y la relación entre las imágenes y los objetivos educativos del software. Los resultados indicaron que tanto la calidad técnica como el contenido del software fueron calificados como "Muy Adecuados". Además, la funcionalidad, la motivación individual y los aspectos de diseño fueron evaluados positivamente, demostrando su eficacia como recurso educativo en el área de la Estomatología​​​​.', 
'Estudio No Experimental Mediante Encuesta Basado en una Muestra No Representativa', 
'Transversal', 
'',
'Sesgo de Conveniencia, Sesgo de Deseabilidad Social',
'Cuba',
7, 
'Software');

CALL InsertarDatosArticulo('L Peraza Cruz, K Galvizu Díaz', 
'Propuesta didáctica de una innovación educativa con las nuevas tecnologías en las Ciencias Básicas Biomédicas', 
2021,
'http://scielo.sld.cu/scielo.php?pid=S1608-89212021000200027&script=sci_arttext', 
'El documento describe una propuesta didáctica innovadora utilizando nuevas tecnologías en las Ciencias Básicas Biomédicas. Esta propuesta se centra en el uso de la plataforma Moodle para crear espacios de aprendizaje en línea y se aplica en la asignatura de Metabolismo-Nutrición, parte de la disciplina Bases Biológicas de la Medicina. Se propone la simulación de una práctica de laboratorio modificada, fomentando el aprendizaje activo, colaborativo y personalizado, con el docente actuando como facilitador del proceso​​.', 
'Los efectos de la intervención educativa incluyen: mejora en la planificación y organización de las actividades docentes; fomento del aprendizaje autónomo, flexible y autorregulado; promoción de la comunicación y el intercambio de ideas; estimulación de la responsabilidad, el aprendizaje colaborativo y la valoración crítica; apoyo al aprendizaje personalizado atendiendo a necesidades cognitivas individuales​​.', 
'No se especifica de forma sufciciente la metodología empleada', 
'Transversal', 
'',
'',
'Cuba',
7, 
'Software');

CALL InsertarDatosArticulo('L de la Hoz Rojas, LS Bermúdez, JDS Díaz', 
'Software educativo sobre patogenia de la enfermedad periodontal inmunoinflamatoria crónica en Periodoncia', 
2020,
'https://www.medigraphic.com/cgi-bin/new/resumen.cgi?IDARTICULO=98284', 
'La intervención innovadora descrita en el documento es el desarrollo de un software educativo. Este software fue diseñado como una herramienta didáctica y bibliográfica para el estudio del tema "Etiología y patogenia de la enfermedad periodontal inmunoinflamatoria crónica" en la asignatura de Periodoncia. El software incluye varios recursos informáticos que facilitan el aprendizaje, tales como tres botones con hipervínculos a los contenidos, videos, curiosidades, bibliografías básica y complementaria, y casos problemas. Se destaca su utilidad en el aprendizaje, permitiendo el acceso tanto desde móviles como computadoras, con facilidades de navegación e interacción, y contenidos actualizados y relevantes​​​​.', 
'El software educativo generó varios efectos positivos. Fue bien recibido tanto por especialistas como por estudiantes, quienes evaluaron favorablemente su diseño, utilidad, facilidad de interacción y aplicabilidad. Los estudiantes destacaron la facilidad de manejo del software, su organización y la contribución que aporta para facilitar el estudio del tema. Además, se observó que el software mantiene la motivación del alumno y presenta información actualizada en correspondencia con los objetivos de la asignatura​​​​.', 
'Estudio No Experimental Mediante Encuesta Basado en una Muestra No Representativa', 
'Transversal', 
'Sesgo de Conveniencia',
'Sesgo de Autoselección, Sesgo de Deseabilidad Social',
'Cuba',
6, 
'Software');

CALL InsertarDatosArticulo('F Hernández-García, JI Robaina-Castillo', 
'Oncopedia, software educativo para el aprendizaje de la oncología pediátrica en la carrera de Medicina', 
2020,
'https://www.scielo.org.mx/scielo.php?pid=S2007-50572020000300028&script=sci_arttext', 
'El documento describe varias intervenciones innovadoras en el campo de la educación médica, centradas en el uso de software educativo. Por ejemplo, se menciona "Oncopedia", un software educativo para el aprendizaje de la oncología pediátrica, y "FarmacOft", un software para la farmacología contra las afecciones oftalmológicas. Estas herramientas están diseñadas para facilitar el aprendizaje en medicina a través de medios digitales y mejorar la comprensión de temas complejos como la oncología pediátrica y la farmacología oftalmológica.', 
'Se observaron varios efectos positivos de estas intervenciones educativas. Por ejemplo, "Oncopedia" fue evaluada positivamente tanto por expertos como por usuarios, quienes la consideraron una herramienta muy adecuada para el aprendizaje de contenidos relacionados con el cáncer en la infancia. Se destaca su interactividad, el uso de materiales audiovisuales y la capacidad de facilitar la solución de problemas médicos en oncopediatría.', 
'Estudio No Experimental Mediante Encuesta Basado en una Muestra Representativa', 
'Transversal', 
'Sesgo de Conveniencia',
'Sesgo de No Respuesta, Sesgo de Cobertura, Sesgo de Deseabilidad Social',
'México',
5, 
'Software');

CALL InsertarDatosArticulo('AG Orozco, OL Pérez, JKC López', 
'Entorno virtual de aprendizaje: las redes sociales para aprender en la universidad', 
2022,
'https://revistas.uma.es/index.php/innoeduca/article/view/12340', 
'Se diseñó un Entorno Virtual de Aprendizaje (EVA) a través de Facebook, utilizado como herramienta complementaria a la enseñanza presencial. La intervención se llevó a cabo durante seis meses con 74 estudiantes de licenciatura. Se destacó por su enfoque en el aprendizaje mixto y el modelo híbrido de aprendizaje, integrando el análisis curricular y la conformación de Comunidades Virtuales de Aprendizaje​​.', 
'La implementación del EVA generó un cambio en la interacción y el proceso de enseñanza y aprendizaje, fomentando la autonomía del estudiante y la participación activa. La diversidad de formatos de material didáctico (infografías, videos, etc.) proporcionó al estudiante acceso a variados contenidos, promoviendo un aprendizaje asincrónico y motivacional​​.', 
'Estudio de Caso Cualitativo', 
'Transversal', 
'',
'Sesgo del Observador, Sesgo de Retrospección, Sesgo Temporal, Sesgo de Narrativa, Sesgo de Generalización',
'México',
5, 
'Software');

CALL InsertarDatosArticulo('M Gutiérrez-Segura, AM Ruiz-Piedra', 
'Empleo de software educativo por los profesores de Rehabilitación, Holguín. Septiembre 2019-enero 2020', 
2020,
'https://revista.uch.edu.pe/index.php/hgh/article/view/67', 
'El documento describe una intervención innovadora que consiste en el empleo de software educativo por parte de los profesores de las asignaturas Rehabilitación I y II en la Universidad de Ciencias Médicas de Holguín. Esta intervención se centra en la utilización de herramientas tecnológicas en el proceso de enseñanza-aprendizaje, especialmente en el área de prótesis estomatológica. El software educativo se emplea en diferentes formas de organización de la enseñanza, como conferencias, trabajo independiente, clases taller, prácticas, teóricas, seminarios y educación en el trabajo. Su propósito varía desde motivar y debatir contenidos hasta interpretar imágenes, realizar ejercicios, evaluar y orientar el estudio independiente.', 
'Los efectos de esta intervención incluyen una mayor interactividad y adaptabilidad del proceso educativo a las necesidades individuales de los estudiantes. El software educativo permite a los estudiantes revisar contenidos y utilizar diversos recursos acorde a sus intereses y ritmo de aprendizaje. Facilita la consolidación y retroalimentación del conocimiento mediante la correspondencia entre contenido, imágenes y ejercicios. Además, promueve un mayor uso e interactividad, mejorando así el estudio independiente y la motivación de los estudiantes.', 
'Estudio No Experimental Mediante Encuesta Basado en una Muestra No Representativa', 
'Transversal', 
'Sesgo de Selección de la Muestra, Sesgo de Conveniencia',
'Sesgo de Autoselección, Sesgo de Conveniencia, Sesgo de Deseabilidad Social',
'Cuba',
5, 
'Software');

CALL InsertarDatosArticulo('EMF Nessi, D Sulbarán, H Carvajal', 
'Educación a Distancia de Emergencia: Innovación Educativa o Improvisación', 
2021,
'https://dialnet.unirioja.es/servlet/articulo?codigo=7984404', 
'La investigación describe una intervención innovadora en el contexto de la educación a distancia de emergencia, implementada en respuesta a la pandemia de COVID-19 en la Universidad Politécnica Territorial del Zulia, Venezuela. Esta innovación involucra cambios significativos en el proceso de enseñanza-aprendizaje, incluyendo los materiales utilizados, los métodos de entrega de las sesiones, los contenidos y los contextos de enseñanza. Aspectos como la tecnología, la didáctica y la pedagogía juegan un papel crucial en esta innovación. La intervención se caracteriza por la creatividad de los docentes y requiere apoyo institucional para su diseminación y escalabilidad​​.', 
'Los efectos generados por esta intervención incluyen el uso extendido de herramientas tecnológicas por parte de los docentes para mantener la comunicación con sus estudiantes, destacando el uso del correo electrónico y WhatsApp para guiar las actividades de enseñanza-aprendizaje. A pesar de enfrentar problemas como cortes eléctricos y fallos en el servicio de internet y datos móviles, los docentes se adaptaron a la modalidad a distancia, realizando esfuerzos significativos para llevar a cabo las actividades educativas. Esta situación llevó a una reflexión y avance en el rol docente durante la pandemia, implicando la necesidad de crear, diseñar e innovar en los procesos de enseñanza-aprendizaje y mantener un pensamiento flexible para transformar la práctica docente​​.', 
'Estudio No Experimental Mediante Encuesta Basado en una Muestra No Representativa', 
'Transversal', 
'Sesgo de Selección de la Muestra, Sesgo de No Respuesta, Sesgo de Conveniencia',
'Sesgo de Autoselección, Sesgo de Cobertura, Sesgo de Deseabilidad Social, Sesgo de Recordatorio',
'Venezuela',
5, 
'Software');

CALL InsertarDatosArticulo('I Centurión César, C Lara', 
'El uso de la rúbrica para evaluar tareas en entornos virtuales de aprendizaje: un caso aplicado a estudiantes avanzados de la carrera de economía', 
2021,
'https://www.colibri.udelar.edu.uy/jspui/handle/20.500.12008/26635', 
'En el documento se describe una intervención innovadora consistente en la implementación de una rúbrica para la evaluación de tareas en entornos virtuales de aprendizaje, aplicada específicamente a un curso avanzado de economía. Esta intervención surgió como respuesta a la necesidad de adaptación a la enseñanza remota durante la pandemia, lo que representó un desafío significativo tanto para docentes como para estudiantes. La innovación incluyó la entrega de un trabajo individual y el diseño de una rúbrica para su corrección, todo implementado en el entorno virtual de aprendizaje. La rúbrica tenía como objetivo transmitir con claridad a los estudiantes lo que se esperaba del producto a entregar y proporcionar a los docentes un criterio uniforme para la corrección de los trabajos​​.', 
'La aplicación de esta rúbrica generó varios efectos positivos. Los resultados obtenidos por los estudiantes fueron mejores en comparación con las evaluaciones tradicionales. La nota promedio fue de 29 sobre 40 puntos, y solamente 14 de 216 trabajos recibieron una calificación menor a 20 puntos. Además, la calidad de los trabajos escritos fue acorde a lo esperado, logrando que los estudiantes realizaran trabajos auténticos, sin plagios ni copias. El seguimiento de los docentes y la entrega anticipada de la rúbrica permitieron a los estudiantes conocer los criterios de corrección y un rango de la calificación final que podrían obtener. Los estudiantes valoraron muy favorablemente la propuesta de trabajo individual y su formato de evaluación, según un cuestionario anónimo realizado al finalizar el curso​​', 
'Estudio de Caso Cualitativo', 
'Transversal', 
'',
'Sesgo del Observador, Sesgo de Narrativa, Sesgo de Generalización',
'Uruguay',
4, 
'Software');

CALL InsertarDatosArticulo('GN Salcedo, JCG Santoyo', 
'Los desafíos en la implementación de aplicaciones educativas en el alumno y su función para incentivar la Educación Superior: The challenges in the implementation of educational applications in the student and its function to encourage Higher', 
2022,
'https://terc.mx/index.php/terc/article/view/267', 
'Sí, el documento describe la incorporación de estrategias didácticas que utilizan software educativo en la enseñanza universitaria. Este enfoque incluye la aplicación de tecnologías de la información y la comunicación (TIC) para desarrollar competencias en los estudiantes, facilitando un aprendizaje interactivo y dinámico en la educación superior.', 
'El efecto principal de esta intervención innovadora es el desarrollo de competencias en los estudiantes a través de la utilización de aplicaciones educativas. Se enfatiza la importancia de establecer patrones para la intervención de las estrategias didácticas, utilizando estas aplicaciones como elementos distintivos en la actividad estudiantil.', 
'Estudio No Experimental Mediante Encuesta Basado en una Muestra Representativa', 
'Longitudinal', 
'Sesgo de Selección de la Muestra, Sesgo de Conveniencia',
'Sesgo de Cobertura, Sesgo de Recordatorio',
'México',
4, 
'Software');

CALL InsertarDatosArticulo('I Guerra Macías, JR Domínguez Pérez', 
'PeritonitiSoft, una herramienta para el aprendizaje de la peritonitisaguda', 
2022,
'http://scielo.sld.cu/scielo.php?pid=S0138-65572022000200024&script=sci_arttext&tlng=en', 
'El documento describe la creación de un software educativo como una innovación tecnológica en la Universidad de Ciencias Médicas de Santiago de Cuba. Este software se desarrolló como una herramienta de consulta didáctica para recopilar contenidos sobre la peritonitis aguda (PA), con el fin de permitir la autopreparación y la revisión independiente de los profesionales de la salud sobre este tema.', 
'El efecto del software educativo sobre los usuarios y expertos en informática fue evaluado mediante un modelo de recogida de datos autoaplicado. Los usuarios consideraron "muy adecuado" el software en aspectos como la validez científica del tema, la organización del contenido, la terminología quirúrgica, la originalidad del diseño, la facilidad de navegación, la utilidad para el aprendizaje y la calidad de las imágenes.', 
'Estudio No Experimental Mediante Encuesta Basado en una Muestra No Representativa', 
'Transversal', 
'Sesgo de Conveniencia',
'Sesgo de Selección de la Muestra, Sesgo de Deseabilidad Social',
'Cuba',
3, 
'Software');

CALL InsertarDatosArticulo('RL Ferrer, YC Robert, YT Sánchez', 
'Entorno virtual de aprendizaje de Genética Médica en tiempos de la COVID-19 en la Facultad de medicina Finlay-Albarrán', 
2021,
'https://www.medigraphic.com/cgi-bin/new/resumen.cgi?IDARTICULO=107554', 
'El documento describe la experiencia del Entorno Virtual de Aprendizaje (EVA) en la asignatura de Genética Médica para estudiantes de Medicina, desarrollada durante el periodo de aislamiento social por la pandemia COVID-19. Este EVA se implementó en la plataforma Moodle, incorporando diversas herramientas didácticas y sesiones de asesoramiento genético en tiempo real, disponibles en el entorno virtual​​​​.', 
'La intervención con EVA en la educación a distancia tuvo varios efectos. Permitió la continuidad del proceso educativo durante la emergencia epidemiológica, facilitó el estudio independiente y la interacción virtual a través de foros de discusión, chat y evaluaciones tipo test. Además, se subraya la importancia de capacitar a profesores y alumnos en el uso de la plataforma para construir conocimientos de manera activa y flexible​​​​​​.', 
'Estudio de Caso Cualitativo', 
'Transversal', 
'',
'Sesgo del Observador, Sesgo de Publicación',
'Cuba',
3, 
'Software');

CALL InsertarDatosArticulo('MJ Cala-Pérez, I Rodríguez-Pérez', 
'Resultados de la implementación del software educativo sobre la salud sexual y reproductiva', 
2022,
'http://scielo.sld.cu/scielo.php?pid=S1025-02552022000100004&script=sci_arttext', 
'El documento describe el uso de un software educativo como una intervención innovadora. Este software se presenta como una herramienta motivadora y efectiva en diferentes escenarios docentes, especialmente en el proceso docente educativo. Se estructura lógica y coherentemente, rompiendo con el esquema tradicional de enseñanza y estimulando la independencia cognitiva de los alumnos. Por ejemplo, se menciona un software educativo enfocado en enfermedades de origen hídrico, que permite a los estudiantes adquirir información actualizada y realizar ejercicios para comprobar sus conocimientos, apoyando así la enseñanza.', 
'Los efectos del software educativo incluyen la adquisición de nueva información por parte de los estudiantes y la ampliación de sus conocimientos existentes. Esta herramienta también motiva el estudio independiente y ofrece un soporte a la docencia. Además, el software recibe calificaciones positivas tanto de docentes como de estudiantes, siendo considerado como una herramienta pertinente, actual, de fácil adquisición y que facilita el autoaprendizaje', 
'Estudio No Experimental Mediante Encuesta Basado en una Muestra No Representativa', 
'Transversal', 
'Sesgo de Selección de la Muestra, Sesgo de Conveniencia',
'Sesgo de Cobertura, Sesgo de Deseabilidad Social',
'Cuba',
2, 
'Software');

CALL InsertarDatosArticulo('M Robaina Santander, L Ruiz Ortiz', 
'Utilización de los entornos virtuales de aprendizaje en la Ingeniería en Bioinformática', 
2021,
'http://scielo.sld.cu/scielo.php?pid=S2227-18992021000500001&script=sci_arttext', 
'El documento describe una intervención innovadora enfocada en la integración de la didáctica con el uso de tecnologías de la información y la comunicación (TIC). Esta intervención incluye tres elementos clave: 1) inclusión de la representación del conocimiento mediante software o plataformas que lo faciliten; 2) incorporación de estrategias de argumentación implementadas a través de un entorno virtual de aprendizaje; 3) desarrollo de actividades de trabajo colaborativo. El propósito de esta innovación es contribuir a la formación de estudiantes en modalidades de educación a distancia, virtual o bimodal, superando desafíos en sus procesos formativos. Se espera que esta innovación aporte significativamente a los procesos sustanciales de la educación superior, especialmente en la formación en la carrera de Ingeniería en Bioinformática, a través de la preparación didáctica y tecnológica de los docentes y el autoaprendizaje de los estudiantes​​.', 
'Los efectos esperados de la intervención son diversos y significativos, enfocados en mejorar los procesos formativos y la preparación didáctica y tecnológica de los docentes. Algunos de los efectos clave son: 1) mejora en la autogestión del aprendizaje de los estudiantes, lo que conduce a un mejor desempeño profesional y a un cambio en el modelo de aprendizaje; 2) contribuciones a la sostenibilidad del sector femenino como ente transformador de la sociedad, a través de la participación económica, el enriquecimiento de conocimientos y el prestigio social; 3) desarrollo de capacidades para sostener ingresos necesarios para mantener los efectos positivos una vez concluido el proyecto; 4) generación de conocimientos mediante la utilización de entornos virtuales de aprendizaje (EVA) y recursos educativos, reforzando la preparación didáctica y tecnológica de los docentes​​.', 
'Estudio Experimental', 
'Transversal', 
'',
'Sesgo de Hawthorne',
'Cuba',
2, 
'Software');

CALL InsertarDatosArticulo('VC Avendaño Porras', 
'Ergonomía digital y su influencia en el aprovechamiento académico de las clases virtuales en enfermería', 
2022,
'https://www.scielo.org.mx/scielo.php?pid=S2007-21712022000100017&script=sci_arttext', 
'El documento describe la implementación de ambientes virtuales de aprendizaje (AVA) en la Escuela de Enfermería de la Universidad Mesoamericana (UNIMESO) como una intervención innovadora. Estos AVA incluyen plataformas de videoconferencias para clases sincrónicas y asincrónicas, así como un espacio en la plataforma UNIMESO Virtual para interacción adicional entre estudiantes y docentes. Esta implementación se realizó para facilitar la educación virtual en respuesta a las restricciones sanitarias impuestas por la pandemia de COVID-19​​.', 
'La implementación de los AVA tuvo varios efectos, tanto positivos como negativos. Positivos: Los estudiantes se adaptaron adecuadamente a los AVA a pesar de las limitaciones tecnológicas y de acceso a Internet. El uso de estas plataformas permitió la continuación del aprendizaje y la interacción entre estudiantes y docentes​​. Negativos: La mayoría de los estudiantes enfrentaron problemas como iluminación inadecuada, ruido de fondo, y falta de mobiliario ergonómico, lo que generó distracción, cansancio y disconfort durante las clases virtuales. Además, se observaron problemas de salud física relacionados con malas posturas debido a la falta de mobiliario adecuado​​.', 
'Estudio No Experimental Mediante Encuesta Basado en una Muestra Representativa', 
'Transversal', 
'',
'Sesgo de Conveniencia, Sesgo de Cobertura, Sesgo de Deseabilidad Social, Sesgo de Recordatorio',
'México',
10, 
'Software');

CALL InsertarDatosArticulo('CAN Brenes', 
'El Modelo de Indagación como Metodología de apoyo en un Curso de Inglés Integrado', 
2023,
'https://revistas.utn.ac.cr/index.php/yulok/article/view/570', 
'El documento describe una intervención innovadora en el ámbito de la educación universitaria, específicamente en un curso de inglés integrado. Esta intervención consiste en el uso del "Modelo de Indagación" como metodología de apoyo, enfocándose en la mejora del proceso de enseñanza-aprendizaje mediante metodologías activas apoyadas en las Tecnologías de la Información y la Comunicación (TIC). La propuesta incluye la planificación de secuencias didácticas y el uso de herramientas digitales en un entorno virtual, buscando generar un cambio en la metodología tradicional y posicionar al estudiante en un punto central del proceso educativo, con el docente actuando como guía y facilitador.', 
'Los efectos generados por esta intervención incluyen una mayor efectividad en la evaluación oral, tanto parcial como final. Se observó un interés de los estudiantes por actividades más interactivas y retadoras, así como la necesidad de retroalimentación después de completar actividades. También se identificaron algunos retos y limitaciones asociados con las sesiones sincrónicas y la cantidad de contenidos del curso. La investigación destaca la importancia de adaptar las metodologías y herramientas digitales a las necesidades y características específicas del curso y de los estudiantes.', 
'Estudio No Experimental Mediante Encuesta Basado en una Muestra No Representativa', 
'Transversal', 
'Sesgo de Conveniencia',
'Sesgo de Cobertura, Sesgo de Deseabilidad Social',
'Costa Rica',
2, 
'Software');

CALL InsertarDatosArticulo('MP Quezada Castro, CA Dios Castillo', 
'Características del estudiante de derecho empresarial y entorno virtual de aprendizaje sincrónico', 
2022,
'https://repositorio.utp.edu.pe/handle/20.500.12867/5840', 
'El documento describe una intervención innovadora en el ámbito educativo, específicamente en el uso de las Tecnologías de la Información y Comunicación (TIC) en la educación superior. Se realizó un estudio en una universidad privada en Piura, Perú, con estudiantes de Derecho Empresarial que interactuaban por primera vez en un entorno virtual de aprendizaje. La intervención se centró en identificar el perfil del estudiante utilizando una rúbrica analítica, con metodologías como enfoque cualitativo, investigación-acción, métodos analítico-sintéticos y observación participante. La motivación del docente y la interacción en el entorno virtual fueron cruciales para incentivar la responsabilidad y participación activa de los estudiantes.', 
'Los efectos de la intervención incluyeron un aumento en la responsabilidad, respeto, predisposición a aprender, autodisciplina, empatía, participación voluntaria, interacción, creatividad e innovación entre los estudiantes. Aunque no todos los estudiantes cumplieron con el 100% de las actividades, se destacó la necesidad de continuar desarrollando habilidades digitales en la enseñanza-aprendizaje. La modalidad sincrónica de la intervención también facilitó una retroalimentación oportuna y benefició el proceso educativo', 
'Estudio de Caso Cualitativo', 
'Transversal', 
'Sesgo de Selección del Caso, Sesgo Temporal',
'Sesgo del Observador, Sesgo de Accesibilidad a la Información',
'Perú',
1, 
'Software');

CALL InsertarDatosArticulo('C Tapia', 
'Moodle un Entorno Virtual de Aprendizaje que promueve el trabajo autónomo y el pensamiento crítico', 
2022,
'http://www.scielo.org.bo/scielo.php?pid=S2616-79642022000502238&script=sci_arttext', 
'La intervención innovadora descrita en el documento se centra en el uso de Entornos Virtuales de Aprendizaje (EVA) para promover el trabajo colaborativo y las estrategias de aprendizaje en jóvenes universitarios. Una característica novedosa de los EVA es la integración de recursos semióticos como el lenguaje oral y escrito, audiovisual, gráfico o numérico, y las posibilidades de comunicación, intercambio, acceso y procesamiento de la información​​.', 
'Los efectos de esta intervención incluyen mayor flexibilidad en el espacio virtual, promoción de la interacción, uso de más elementos audiovisuales en el desarrollo de temas, y la adecuación para fortalecer el trabajo autónomo y el aprendizaje de los estudiantes. Además, se menciona que la plataforma Moodle, utilizada en los EVA, proporciona herramientas que permiten el desarrollo del trabajo autónomo de los estudiantes y puede fomentar habilidades del pensamiento crítico que deben ser incorporadas al proceso educativo​​​​.', 
'Revisión Sistemática', 
'Transversal', 
'Sesgo de Idioma',
'Sesgo de Publicación, Sesgo de Selección de Estudios, Sesgo de Confirmación, Sesgo de Financiamiento, Sesgo de Citación',
'Ecuador',
1, 
'Software');

CALL InsertarDatosArticulo('AH Navarro Huaringa, GS Raggio Ramirez', 
'Software educativo en el aprendizaje de los estudiantes universitarios', 
2023,
'http://www.scielo.org.bo/scielo.php?pid=S2616-79642022000401375&script=sci_arttext', 
'Sí, el documento describe una intervención innovadora. Se trata de una contribución a las innovaciones pedagógicas en la educación universitaria a través del uso de materiales educativos como los softwares y las tecnologías de la información y la comunicación. Este enfoque se implementó con el objetivo de demostrar las ventajas de estos recursos educativos para el aprendizaje de los estudiantes. La investigación justifica teóricamente la importancia de implementar softwares educativos como parte del modelo metodológico para la enseñanza de estudiantes universitarios, basándose en sus principios técnicos, pedagógicos y tecnológicos. Estos aspectos son cruciales para la selección de softwares educativos, con el objetivo de fortalecer el proceso de enseñanza y aprendizaje. Además, la investigación podría adaptarse a otras instituciones educativas de diferentes niveles, como instituciones de educación básica', 
'Los efectos de la intervención se describen claramente en el documento. Se menciona que los softwares educativos influyen positivamente en el aprendizaje de los estudiantes universitarios. Esta influencia se manifiesta en las dimensiones pedagógica, técnica y tecnológica de los softwares educativos. Se realizaron pruebas estadísticas, como la prueba de Wald, para determinar la influencia de una variable en otra. Los resultados de estas pruebas confirmaron que tanto la dimensión pedagógica como la técnica de los softwares educativos tienen un impacto positivo en el aprendizaje de los estudiantes universitarios.', 
'Estudio No Experimental Mediante Encuesta Basado en una Muestra No Representativa', 
'Transversal', 
'',
'',
'Perú',
1, 
'Software');

CALL InsertarDatosArticulo('RAC Valle, EC Molina, MDL Noriega', 
'Influencia de un entorno virtual de aprendizaje en la práctica profesional de enfermería', 
2022,
'https://revista.redipe.org/index.php/1/article/view/1697', 
'Se describe una intervención innovadora que implica la implementación de un entorno virtual de aprendizaje para la enseñanza de la Metodología del Proceso de Atención de Enfermería (MPAE). Esta intervención se centra en mejorar la práctica profesional de enfermería a través de un enfoque educativo basado en e-learning. Se utilizó el modelo ADDIE para el diseño instruccional y se enfocó en la aplicación de la MPAE en los registros clínicos de enfermería (página 2).', 
'Los efectos de esta intervención incluyen un incremento significativo en las competencias y desempeño del personal de enfermería en las cuatro dimensiones evaluadas: valoración, diagnóstico, planeación-ejecución y evaluación. Se reportó una mejora sustancial en la aplicabilidad de la MPAE, reflejada en el aumento del nivel de cumplimiento de los participantes en la evaluación post-intervención (página 7)', 
'Estudio Cuasi-Experimental', 
'Transversal', 
'',
'Sesgo de Hawthorne, Sesgo de Confirmación',
'México',
1, 
'Software');

CALL InsertarDatosArticulo('GM Adrian', 
'Software educativo para el desarrollo de la electroterapia en estudiantes de rehabilitación en salud', 
2023,
'https://bibliotecass.sld.cu/index.php/bibliotecass2023/2023/paper/view/49', 
'Se diseñó un software educativo para mejorar los conocimientos en electroterapia entre los estudiantes de la carrera Rehabilitación en Salud. Este software, portátil y accesible en diversos dispositivos, incluía literatura, imágenes y videos, y estaba enfocado en mejorar la identificación de gráficos de corrientes terapéuticas y en incrementar el conocimiento de técnicas, indicaciones y contraindicaciones de dichas corrientes en un contexto docente.', 
'La implementación del software educativo llevó a un aumento significativo en el conocimiento de los estudiantes. Antes de usar el software, solo el 16,66% de los estudiantes podían identificar correctamente los gráficos de corrientes terapéuticas, pero después de la intervención, esta cifra aumentó al 83,33%. También se observó un aumento en los conocimientos sobre los efectos de las corrientes en el organismo, de un 33,33% a un 58,33%. Además, el 100% de los estudiantes lograron aprender las técnicas de aplicación de las corrientes analgésicas y estimulantes.', 
'Estudio No Experimental Mediante Encuesta Basado en una Muestra No Representativa', 
'Transversal', 
'',
'Sesgo de Autoselección, Sesgo de Conveniencia, Sesgo de Deseabilidad Social',
'Cuba',
10, 
'Software');

CALL InsertarDatosArticulo('AM Martín-Cuadrado, FJ Spanhol', 
'Competencias digitales e innovación educativa en la conversión de curso presencial en curso virtual durante la pandemia de COVID-19', 
2021,
'https://www.aunirede.org.br/revista/index.php/emrede/article/view/808', 
'El documento describe una intervención innovadora en el ámbito de la educación virtual. Se utilizó el Aprendizaje Basado en Problemas (ABP) en un entorno virtual de aprendizaje desarrollado en Moodle. Esta metodología se diseñó para ser transversal al curso, permitiendo a los estudiantes aplicar lo aprendido en la resolución de problemáticas reales, con la guía del equipo docente. La tutorización virtual se llevó a cabo principalmente a través del correo electrónico y foros, enfocándose en aspectos relevantes del curso y facilitando la interacción entre docentes y participantes​​.', 
'Los efectos de esta intervención incluyen el desarrollo de competencias digitales, la mejora en la comunicación y colaboración digital de los participantes, y el intercambio de experiencias entre ellos. Se resalta la importancia de adaptar la educación a la virtualidad, especialmente en el contexto de la pandemia de COVID-19. El curso fomentó la curiosidad de conocer realidades entre países vecinos y permitió la reutilización de ciertas acciones y soluciones a problemas no identificados previamente. Además, se destaca la importancia de una conexión de calidad y el uso de material educativo en formatos ligeros para facilitar el acceso​​​​.', 
'Estudio de Caso Cualitativo', 
'Transversal', 
'',
'Sesgo de Selección del Caso',
'Panamá, Argentina, Brasil',
1, 
'Software');

