CALL InsertarDatosArticulo('Damián Del Valle', 
'La universidad argentina pre y post pandemia: acciones frente al Covid-19 y los desafíos de una (posible) reforma.', 
2021,
'https://dialnet.unirioja.es/servlet/articulo?codigo=8171321', 
'El documento describe diversas acciones implementadas por las universidades argentinas en respuesta a la pandemia de COVID-19. Estas acciones incluyen la adaptación a la virtualidad, el fortalecimiento de la cooperación en redes académicas, y el desarrollo de políticas para el acceso y difusión del conocimiento científico-tecnológico. También se menciona la generación de contenidos educativos en canales como Paka Paka, Encuentro, y Deportv, y el papel de las universidades en la internacionalización en el contexto de la pandemia​​​​​​.', 
'Los efectos de estas intervenciones son variados. Incluyen la visibilización de desigualdades y brechas tecnológicas, el impacto en cuestiones de género, y la revalorización del rol de las universidades como bien público y social. También se observa una mayor importancia de la transdisciplinariedad para resolver problemas complejos y el replanteamiento de la internacionalización universitaria a raíz de la pandemia​​​​​​.', 
'No se especifíca de forma suficiente la metodología empleada', 
'', 
'',
'',
'Argentina',
32, 
'Creenciales Alternativas');

CALL InsertarDatosArticulo('Daniela Perrotta', 
'La universidad argentina pre y post pandemia: acciones frente al Covid-19 y los desafíos de una (posible) reforma.', 
2021,
'https://dialnet.unirioja.es/servlet/articulo?codigo=8171321', 
'El documento describe diversas acciones implementadas por las universidades argentinas en respuesta a la pandemia de COVID-19. Estas acciones incluyen la adaptación a la virtualidad, el fortalecimiento de la cooperación en redes académicas, y el desarrollo de políticas para el acceso y difusión del conocimiento científico-tecnológico. También se menciona la generación de contenidos educativos en canales como Paka Paka, Encuentro, y Deportv, y el papel de las universidades en la internacionalización en el contexto de la pandemia​​​​​​.', 
'Los efectos de estas intervenciones son variados. Incluyen la visibilización de desigualdades y brechas tecnológicas, el impacto en cuestiones de género, y la revalorización del rol de las universidades como bien público y social. También se observa una mayor importancia de la transdisciplinariedad para resolver problemas complejos y el replanteamiento de la internacionalización universitaria a raíz de la pandemia​​​​​​.', 
'No se especifíca de forma suficiente la metodología empleada', 
'', 
'',
'',
'Argentina',
32, 
'Creenciales Alternativas');

CALL InsertarDatosArticulo('Claudio Suasnábar', 
'La universidad argentina pre y post pandemia: acciones frente al Covid-19 y los desafíos de una (posible) reforma.', 
2021,
'https://dialnet.unirioja.es/servlet/articulo?codigo=8171321', 
'El documento describe diversas acciones implementadas por las universidades argentinas en respuesta a la pandemia de COVID-19. Estas acciones incluyen la adaptación a la virtualidad, el fortalecimiento de la cooperación en redes académicas, y el desarrollo de políticas para el acceso y difusión del conocimiento científico-tecnológico. También se menciona la generación de contenidos educativos en canales como Paka Paka, Encuentro, y Deportv, y el papel de las universidades en la internacionalización en el contexto de la pandemia​​​​​​.', 
'Los efectos de estas intervenciones son variados. Incluyen la visibilización de desigualdades y brechas tecnológicas, el impacto en cuestiones de género, y la revalorización del rol de las universidades como bien público y social. También se observa una mayor importancia de la transdisciplinariedad para resolver problemas complejos y el replanteamiento de la internacionalización universitaria a raíz de la pandemia​​​​​​.', 
'No se especifíca de forma suficiente la metodología empleada', 
'', 
'',
'',
'Argentina',
32, 
'Creenciales Alternativas');

CALL InsertarDatosArticulo('ME Cortés Cortés', 
'Ventajas de la plataforma Moodle para la enseñanza de las matemáticas en la universidad de Cienfuegos', 
2020,
'http://scielo.sld.cu/scielo.php?pid=S2218-36202020000600240&script=sci_arttext&tlng=pt', 
'Se describe la integración de las Tecnologías de la Información y Comunicación (TIC) en el aula, enfocándose particularmente en el uso de YouTube como herramienta educativa. Esta intervención innovadora responde a la necesidad de adaptarse a la "sociedad de la información", donde las TIC son fundamentales. Los cambios significativos incluyen el manejo y transmisión casi inmediata de grandes cantidades de información, lo que plantea retos para las instituciones educativas a nivel global. Un aspecto notable de esta intervención es la adaptación de las prácticas educativas al entorno digital, impulsada por la emergencia sanitaria del COVID-19 y el consiguiente cierre de escuelas.', 
'Los efectos de esta intervención incluyen un aprendizaje diverso y aplicable en diferentes ámbitos de la vida de los estudiantes. Se observa que los estudiantes perciben un aprendizaje significativo a través de los videos, aplicándolos en contextos académicos y personales. A pesar del desafío relacionado con la fiabilidad de la información, los estudiantes logran recuperar conocimientos significativos incluso de contenidos considerados como de entretenimiento, como la música.', 
'Estudio Cuasi-Experimental', 
'Transversal', 
'Sesgos P',
'Sesgo de Selección , Sesgo de Medición , Sesgo de Confirmación e Investigador',
'Mexico',
17, 
'Creenciales Alternativas');

CALL InsertarDatosArticulo('M Cortés Iglesias', 
'Ventajas de la plataforma Moodle para la enseñanza de las matemáticas en la universidad de Cienfuegos', 
2020,
'http://scielo.sld.cu/scielo.php?pid=S2218-36202020000600240&script=sci_arttext&tlng=pt', 
'Se describe la integración de las Tecnologías de la Información y Comunicación (TIC) en el aula, enfocándose particularmente en el uso de YouTube como herramienta educativa. Esta intervención innovadora responde a la necesidad de adaptarse a la "sociedad de la información", donde las TIC son fundamentales. Los cambios significativos incluyen el manejo y transmisión casi inmediata de grandes cantidades de información, lo que plantea retos para las instituciones educativas a nivel global. Un aspecto notable de esta intervención es la adaptación de las prácticas educativas al entorno digital, impulsada por la emergencia sanitaria del COVID-19 y el consiguiente cierre de escuelas.', 
'Los efectos de esta intervención incluyen un aprendizaje diverso y aplicable en diferentes ámbitos de la vida de los estudiantes. Se observa que los estudiantes perciben un aprendizaje significativo a través de los videos, aplicándolos en contextos académicos y personales. A pesar del desafío relacionado con la fiabilidad de la información, los estudiantes logran recuperar conocimientos significativos incluso de contenidos considerados como de entretenimiento, como la música.', 
'Estudio Cuasi-Experimental', 
'Transversal', 
'Sesgos P',
'Sesgo de Selección , Sesgo de Medición , Sesgo de Confirmación e Investigador',
'Mexico',
17, 
'Creenciales Alternativas');

CALL InsertarDatosArticulo('SV Balderas', 
'Experiencias de aprendizaje en YouTube, un análisis durante la pandemia de COVID-19', 
2021,
'https://dialnet.unirioja.es/servlet/articulo?codigo=8103329', 
'El documento describe el uso de la plataforma Moodle para la enseñanza de matemáticas en la Universidad de Cienfuegos. Moodle, un entorno de aprendizaje dinámico orientado a objetos y modular, es utilizado para transformar la enseñanza tradicional en una enseñanza más activa, centrada en el estudiante. Se enfatiza en la necesidad de cambios en los sistemas educativos y se promueve el uso intensivo de medios tecnológicos y aplicaciones informáticas en las universidades​​', 
'Los efectos de esta intervención incluyen una mayor interacción del estudiante con la materia a estudiar, la posibilidad de realizar tareas y seminarios con anticipación, y una mejora en la retroalimentación del profesor respecto a la asignatura. Sin embargo, también se mencionan insuficiencias en aprovechar todas las ventajas de esta herramienta, sugiriendo que aún hay espacio para mejorar en su implementación y uso​​.', 
'No se especifíca de forma suficiente la metodología empleada', 
'', 
'',
'',
'Cuba',
15, 
'Creenciales Alternativas');

CALL InsertarDatosArticulo('JM Tapia', 
'Experiencias de aprendizaje en YouTube, un análisis durante la pandemia de COVID-19', 
2021,
'https://dialnet.unirioja.es/servlet/articulo?codigo=8103329', 
'El documento describe el uso de la plataforma Moodle para la enseñanza de matemáticas en la Universidad de Cienfuegos. Moodle, un entorno de aprendizaje dinámico orientado a objetos y modular, es utilizado para transformar la enseñanza tradicional en una enseñanza más activa, centrada en el estudiante. Se enfatiza en la necesidad de cambios en los sistemas educativos y se promueve el uso intensivo de medios tecnológicos y aplicaciones informáticas en las universidades​​', 
'Los efectos de esta intervención incluyen una mayor interacción del estudiante con la materia a estudiar, la posibilidad de realizar tareas y seminarios con anticipación, y una mejora en la retroalimentación del profesor respecto a la asignatura. Sin embargo, también se mencionan insuficiencias en aprovechar todas las ventajas de esta herramienta, sugiriendo que aún hay espacio para mejorar en su implementación y uso​​.', 
'No se especifíca de forma suficiente la metodología empleada', 
'', 
'',
'',
'Cuba',
15, 
'Creenciales Alternativas');

CALL InsertarDatosArticulo('LI González-Pérez', 
'Habilitadores tecnológicos 4.0 para impulsar la educación abierta: aportaciones para las recomendaciones de la UNESCO', 
2022,
'https://repositorio.grial.eu/handle/grial/2591', 
'El documento analiza la implementación de tecnologías 4.0 para impulsar la educación abierta, en línea con las recomendaciones de la UNESCO. Se destaca la estandarización de arquitecturas para integrar laboratorios remotos en ambientes de aprendizaje en línea. Por ejemplo, se menciona un laboratorio remoto implementado en la plataforma eDX usando Learning Tools Interoperability (LTI), y otro ejemplo es el laboratorio Mach-Zehnder Interferometer integrado en una plataforma de medios sociales educativos que utiliza estándares Learning Inquire Space (ILS) sobre hosting en Graasp. Estas implementaciones representan intervenciones innovadoras en el ámbito de la educación abierta, aprovechando tecnologías emergentes para facilitar y enriquecer el aprendizaje en línea​​.', 
'Los efectos de estas intervenciones incluyen contribuciones a las comunidades académicas (estudiantes, profesores, investigadores), las comunidades sociales, el gobierno, las empresas y los responsables de la toma de decisiones. Específicamente, se menciona el impacto en el acceso efectivo, inclusivo y equitativo a Recursos Educativos Abiertos (REA) de calidad, promoviendo su adopción mediante soluciones tecnológicas pertinentes. También se destaca el uso de métodos predictivos en la educación que permitieron un aumento de hasta el 15% en el rendimiento de los alumnos, lo que sugiere una mejora significativa en el aprendizaje y la efectividad educativa​​​​.', 
'Estudio No Experimental Mediante Encuesta Basado en una Muestra Representativa', 
'Transversal', 
'Sesgo de Selección',
'Sesgo de Hawthorne , Sesgo de Medición , Sesgo Temporal',
'Mexico',
13, 
'Creenciales Alternativas');

CALL InsertarDatosArticulo('MS Ramírez-Montoya', 
'Habilitadores tecnológicos 4.0 para impulsar la educación abierta: aportaciones para las recomendaciones de la UNESCO', 
2022,
'https://repositorio.grial.eu/handle/grial/2591', 
'El documento analiza la implementación de tecnologías 4.0 para impulsar la educación abierta, en línea con las recomendaciones de la UNESCO. Se destaca la estandarización de arquitecturas para integrar laboratorios remotos en ambientes de aprendizaje en línea. Por ejemplo, se menciona un laboratorio remoto implementado en la plataforma eDX usando Learning Tools Interoperability (LTI), y otro ejemplo es el laboratorio Mach-Zehnder Interferometer integrado en una plataforma de medios sociales educativos que utiliza estándares Learning Inquire Space (ILS) sobre hosting en Graasp. Estas implementaciones representan intervenciones innovadoras en el ámbito de la educación abierta, aprovechando tecnologías emergentes para facilitar y enriquecer el aprendizaje en línea​​.', 
'Los efectos de estas intervenciones incluyen contribuciones a las comunidades académicas (estudiantes, profesores, investigadores), las comunidades sociales, el gobierno, las empresas y los responsables de la toma de decisiones. Específicamente, se menciona el impacto en el acceso efectivo, inclusivo y equitativo a Recursos Educativos Abiertos (REA) de calidad, promoviendo su adopción mediante soluciones tecnológicas pertinentes. También se destaca el uso de métodos predictivos en la educación que permitieron un aumento de hasta el 15% en el rendimiento de los alumnos, lo que sugiere una mejora significativa en el aprendizaje y la efectividad educativa​​​​.', 
'Estudio No Experimental Mediante Encuesta Basado en una Muestra Representativa', 
'Transversal', 
'Sesgo de Selección',
'Sesgo de Hawthorne , Sesgo de Medición , Sesgo Temporal',
'Mexico',
13, 
'Creenciales Alternativas');

CALL InsertarDatosArticulo('SN Apaza Cano', 
'… de la red social Facebook y su aporte en el aprendizaje colaborativo de los estudiantes del I ciclo de la facultad de arquitectura, en una universidad privada de Lima …', 
2021,
'https://repositorio.utp.edu.pe/handle/20.500.12867/4786', 
'El documento describe una intervención innovadora centrada en el uso del aprendizaje colaborativo, que incluye la incorporación de actividades, videos, audios, links, y repositorios para dinamizar el aula de clase. Esta estrategia didáctica busca motivar a los estudiantes, proporcionando profundidad académica y contribuyendo al desarrollo de habilidades blandas ', 
'Los efectos de esta intervención incluyen una mejora en el rendimiento académico, como se observa en la descripción de un objetivo general de un estudio que investigó la influencia del aprendizaje colaborativo en el rendimiento académico de estudiantes de Química General en la Facultad de Ingeniería Industrial de una universidad privada (página 23). Además, se mencionan las experiencias positivas de los estudiantes al utilizar redes sociales como herramientas educativas, lo que indica un impacto favorable en su aprendizaje (páginas 96, 103).', 
'Estudio de Caso Cualitativo', 
'Transversal', 
'Sesgo de Generalización',
'Sesgo de Selección del Caso , Sesgo del Observador , Sesgo de Accesibilidad a la Información , Sesgo Temporal , Sesgo de Narrativa',
'Peru',
5, 
'Creenciales Alternativas');

CALL InsertarDatosArticulo('DA Bravo Bonifaz', 
'… de la red social Facebook y su aporte en el aprendizaje colaborativo de los estudiantes del I ciclo de la facultad de arquitectura, en una universidad privada de Lima …', 
2021,
'https://repositorio.utp.edu.pe/handle/20.500.12867/4786', 
'El documento describe una intervención innovadora centrada en el uso del aprendizaje colaborativo, que incluye la incorporación de actividades, videos, audios, links, y repositorios para dinamizar el aula de clase. Esta estrategia didáctica busca motivar a los estudiantes, proporcionando profundidad académica y contribuyendo al desarrollo de habilidades blandas ', 
'Los efectos de esta intervención incluyen una mejora en el rendimiento académico, como se observa en la descripción de un objetivo general de un estudio que investigó la influencia del aprendizaje colaborativo en el rendimiento académico de estudiantes de Química General en la Facultad de Ingeniería Industrial de una universidad privada (página 23). Además, se mencionan las experiencias positivas de los estudiantes al utilizar redes sociales como herramientas educativas, lo que indica un impacto favorable en su aprendizaje (páginas 96, 103).', 
'Estudio de Caso Cualitativo', 
'Transversal', 
'Sesgo de Generalización',
'Sesgo de Selección del Caso , Sesgo del Observador , Sesgo de Accesibilidad a la Información , Sesgo Temporal , Sesgo de Narrativa',
'Peru',
5, 
'Creenciales Alternativas');

CALL InsertarDatosArticulo('AM Marruffo Risco', 
'… de la red social Facebook y su aporte en el aprendizaje colaborativo de los estudiantes del I ciclo de la facultad de arquitectura, en una universidad privada de Lima …', 
2021,
'https://repositorio.utp.edu.pe/handle/20.500.12867/4786', 
'El documento describe una intervención innovadora centrada en el uso del aprendizaje colaborativo, que incluye la incorporación de actividades, videos, audios, links, y repositorios para dinamizar el aula de clase. Esta estrategia didáctica busca motivar a los estudiantes, proporcionando profundidad académica y contribuyendo al desarrollo de habilidades blandas ', 
'Los efectos de esta intervención incluyen una mejora en el rendimiento académico, como se observa en la descripción de un objetivo general de un estudio que investigó la influencia del aprendizaje colaborativo en el rendimiento académico de estudiantes de Química General en la Facultad de Ingeniería Industrial de una universidad privada (página 23). Además, se mencionan las experiencias positivas de los estudiantes al utilizar redes sociales como herramientas educativas, lo que indica un impacto favorable en su aprendizaje (páginas 96, 103).', 
'Estudio de Caso Cualitativo', 
'Transversal', 
'Sesgo de Generalización',
'Sesgo de Selección del Caso , Sesgo del Observador , Sesgo de Accesibilidad a la Información , Sesgo Temporal , Sesgo de Narrativa',
'Peru',
5, 
'Creenciales Alternativas');

CALL InsertarDatosArticulo('WH Da Silva Mello', 
'El trabajo docente en tiempos de pandemia, educación remota y desigualdad educativa: percepciones, discursos y prácticas de los y las profesores/as de escuelas', 
2021,
'https://www.memoria.fahce.unlp.edu.ar/library?a=d&c=tesis&d=Jte2048', 
'El documento describe una intervención innovadora enfocada en el uso efectivo de las Tecnologías de la Información y la Comunicación (TICs) en la educación. Se menciona la implementación de cursos para que los docentes empleen las TICs de manera eficaz, considerándolas un elemento clave para lograr reformas educativas significativas y responder a los retos educativos actuales', 
'Los efectos generados por esta intervención incluyen una mayor adaptabilidad y competitividad en el entorno educativo, especialmente en tiempos de crisis sanitaria. Se resalta la importancia de desarrollar competencias digitales en los docentes para mejorar la calidad del servicio educativo y el progreso educativo, económico y social ', 
'Revisión bibliográfica', 
'Transversal', 
'',
'Sesgo de Idioma',
'Mexico',
3, 
'Creenciales Alternativas');

CALL InsertarDatosArticulo('JC Mendoza Cedeño', 
'Implicaciones de la venta ambulante post covid-19 y propuesta de mejoramiento en la logística y distribución de los vendedores ambulantes en el sector Sgto.', 
2020,
'http://repositorio.ug.edu.ec/handle/redug/53304', 
'Implementación de estrategias disruptivas para cambiar mentalidades y prácticas, y la necesidad de un giro pedagógico en la formación docente con énfasis en la justicia social. También se resalta el uso de plataformas y recursos educativos virtuales como alternativas para la continuidad académica, aunque se señalan limitaciones como la falta de acceso a equipos y conexión a Internet y la mínima alfabetización digital entre docentes y estudiantes​​.', 
'Los efectos de estas intervenciones incluyen el cambio en la experiencia de ser y estar en el mundo para estudiantes y docentes, con un enfoque en el aprendizaje virtual. Hubo un incremento significativo en las responsabilidades y exigencias de los docentes, así como en el estrés y la carga de trabajo. Se observa una sobrecarga laboral, particularmente entre las profesoras, y un aumento de problemas de salud mental como ansiedad y estrés entre el magisterio. Además, se resalta la desigualdad en el acceso a la tecnología, lo cual ha exigido un esfuerzo mayor por parte de las Instituciones Formadoras y Actualizadoras de Docentes (IFAD) para mantener el contacto cercano con los estudiantes, especialmente aquellos en regiones con mayores dificultades de conexión y condiciones socioeconómicas desfavorables​​.', 
'Estudio de Caso Cualitativo', 
'Transversaal', 
'Sesgo de Selección del Caso - Sesgo de Accesibilidad a la Información - Sesgo Temporal - Sesgo de Narrativa - Sesgo de Generalización',
'',
'Mexico',
2, 
'Creenciales Alternativas');

CALL InsertarDatosArticulo('DL Flores-Salazar', 
'Coaching socioformativo y desarrollo social sostenible en la educación superior: el gran desafío de ingresar al mercado laboral.', 
2021,
'https://cife.edu.mx/ecocience/index.php/ecocience/article/view/100', 
'El documento describe una intervención innovadora relacionada con programas cortos de educación superior en América Latina y el Caribe. Estos programas incluyen sesiones frecuentes con orientadores y el uso de sitios web interactivos como Naviance en Estados Unidos, que adaptan la información a cada estudiante, sus progenitores y a los orientadores. Estas intervenciones están diseñadas para cambiar las preferencias de los estudiantes al proporcionarles información personalizada y relevante, lo cual se ha demostrado efectivo en datos de Estados Unidos y Chile​​.', 
'Los efectos de estas intervenciones incluyen un cambio en las preferencias y decisiones de los estudiantes, influenciando su comportamiento. Las intervenciones directas, que involucran un contacto personal e intensivo con los estudiantes, como las sesiones de orientación, han demostrado ser efectivas. Por otro lado, las intervenciones indirectas, como la publicación de información en sitios web, no han mostrado un impacto significativo en la conducta de los estudiantes​​.', 
'Revisión bibliográfica', 
'', 
'',
'',
'',
2, 
'Creenciales Alternativas');

CALL InsertarDatosArticulo('B Colombari', 
'Las juventudes de sectores medios de Tierra del Fuego: explorando los efectos del Covid-19 y el aislamiento desde una escala subnacional.', 
2021,
'https://www.scielo.cl/scielo.php?pid=S0718-22362021000200071&script=sci_arttext&tlng=pt', 
'El documento describe una intervención innovadora relacionada con la educación superior, específicamente en el contexto de los MOOC (Cursos Masivos Abiertos en Línea). Se menciona que estas innovaciones en la educación superior suponen una modificación de los cursos de acción convencionales, desafiando el orden institucional y modificando el status quo. Se observa que los funcionarios de la educación superior tienen una buena opinión sobre los MOOC, aunque con un conocimiento parcial e incompleto de sus características. Se identifica a los MOOC como un recurso para la capacitación y formación continua, pero no necesariamente como parte de la formación profesional de estudiantes de licenciatura y posgrado.', 
' Los efectos observados de la implementación de los MOOC incluyen una curva positiva de aprendizaje y un inicio de producción y aprovechamiento de la oferta externa existente. A pesar de esto, se señala que los MOOC no cumplieron con uno de sus principales propósitos, que era atender las necesidades formativas de quienes no tenían acceso a programas académicos de calidad, ya que eran utilizados principalmente por personas con formación universitaria. Además, se menciona la existencia de bajas tasas de eficiencia en su uso.', 
'Estudio No Experimental Mediante Encuesta Basado en una Muestra No Representativa.', 
'', 
'',
'',
'México',
2, 
'Creenciales Alternativas');

CALL InsertarDatosArticulo('L Guzzi', 
'Las juventudes de sectores medios de Tierra del Fuego: explorando los efectos del Covid-19 y el aislamiento desde una escala subnacional.', 
2021,
'https://www.scielo.cl/scielo.php?pid=S0718-22362021000200071&script=sci_arttext&tlng=pt', 
'El documento describe una intervención innovadora relacionada con la educación superior, específicamente en el contexto de los MOOC (Cursos Masivos Abiertos en Línea). Se menciona que estas innovaciones en la educación superior suponen una modificación de los cursos de acción convencionales, desafiando el orden institucional y modificando el status quo. Se observa que los funcionarios de la educación superior tienen una buena opinión sobre los MOOC, aunque con un conocimiento parcial e incompleto de sus características. Se identifica a los MOOC como un recurso para la capacitación y formación continua, pero no necesariamente como parte de la formación profesional de estudiantes de licenciatura y posgrado.', 
' Los efectos observados de la implementación de los MOOC incluyen una curva positiva de aprendizaje y un inicio de producción y aprovechamiento de la oferta externa existente. A pesar de esto, se señala que los MOOC no cumplieron con uno de sus principales propósitos, que era atender las necesidades formativas de quienes no tenían acceso a programas académicos de calidad, ya que eran utilizados principalmente por personas con formación universitaria. Además, se menciona la existencia de bajas tasas de eficiencia en su uso.', 
'Estudio No Experimental Mediante Encuesta Basado en una Muestra No Representativa.', 
'', 
'',
'',
'México',
2, 
'Creenciales Alternativas');

CALL InsertarDatosArticulo('L Kida', 
'Las juventudes de sectores medios de Tierra del Fuego: explorando los efectos del Covid-19 y el aislamiento desde una escala subnacional.', 
2021,
'https://www.scielo.cl/scielo.php?pid=S0718-22362021000200071&script=sci_arttext&tlng=pt', 
'El documento describe una intervención innovadora relacionada con la educación superior, específicamente en el contexto de los MOOC (Cursos Masivos Abiertos en Línea). Se menciona que estas innovaciones en la educación superior suponen una modificación de los cursos de acción convencionales, desafiando el orden institucional y modificando el status quo. Se observa que los funcionarios de la educación superior tienen una buena opinión sobre los MOOC, aunque con un conocimiento parcial e incompleto de sus características. Se identifica a los MOOC como un recurso para la capacitación y formación continua, pero no necesariamente como parte de la formación profesional de estudiantes de licenciatura y posgrado.', 
' Los efectos observados de la implementación de los MOOC incluyen una curva positiva de aprendizaje y un inicio de producción y aprovechamiento de la oferta externa existente. A pesar de esto, se señala que los MOOC no cumplieron con uno de sus principales propósitos, que era atender las necesidades formativas de quienes no tenían acceso a programas académicos de calidad, ya que eran utilizados principalmente por personas con formación universitaria. Además, se menciona la existencia de bajas tasas de eficiencia en su uso.', 
'Estudio No Experimental Mediante Encuesta Basado en una Muestra No Representativa.', 
'', 
'',
'',
'México',
2, 
'Creenciales Alternativas');

CALL InsertarDatosArticulo('BS Santos', 
'¿ Dentro o Fuera de la Universidad? Experiencias de educación superior alternativa: un diálogo entre Boaventura de Sousa Santos y Luis Fernando Cuji …', 
2022,
'https://www.scielo.br/j/edreal/a/LVbX7Mn5RYQGwgPXrJDxSKc/', 
'El documento describe una intervención innovadora en el programa de Ingeniería Mecatrónica de la Universidad Tecnológica de Pereira, enfocándose en la obtención de insignias digitales. Esta iniciativa busca responder a los desafíos de la educación superior en el siglo XXI, ofreciendo flexibilidad curricular y adaptación frente a la contingencia de la pandemia. Las insignias digitales brindan una certificación digital fiable de competencias, resultados de aprendizaje y estrategias adquiridas, facilitando el acercamiento del sector productivo y laboral a las competencias de los estudiantes y permitiendo un despliegue público de la información​​.', 
'La implementación de insignias digitales en el programa de ingeniería mecatrónica ha permitido cambios en el modelo educativo, orientando hacia el desarrollo de capacidades y destrezas creativas, y proporcionando una educación más adaptada a la era digital. Estas insignias ofrecen una visión más amplia y verificable de los aprendizajes y habilidades adquiridas, facilitando la inserción laboral y el reconocimiento de competencias. Además, promueven un aprendizaje significativo y profundo por iniciativa del estudiante, con el apoyo del docente en procesos tanto presenciales como virtuales​​.', 
'Estudio Cuasi-Experimental.', 
'Transversal', 
'',
'Sesgo de Hawthorne , Sesgo de Medición , Sesgo de Confirmación/Sesgo del Investigador',
'Colombia',
1, 
'Creenciales Alternativas');

CALL InsertarDatosArticulo('LFC Llugna', 
'¿ Dentro o Fuera de la Universidad? Experiencias de educación superior alternativa: un diálogo entre Boaventura de Sousa Santos y Luis Fernando Cuji …', 
2022,
'https://www.scielo.br/j/edreal/a/LVbX7Mn5RYQGwgPXrJDxSKc/', 
'El documento describe una intervención innovadora en el programa de Ingeniería Mecatrónica de la Universidad Tecnológica de Pereira, enfocándose en la obtención de insignias digitales. Esta iniciativa busca responder a los desafíos de la educación superior en el siglo XXI, ofreciendo flexibilidad curricular y adaptación frente a la contingencia de la pandemia. Las insignias digitales brindan una certificación digital fiable de competencias, resultados de aprendizaje y estrategias adquiridas, facilitando el acercamiento del sector productivo y laboral a las competencias de los estudiantes y permitiendo un despliegue público de la información​​.', 
'La implementación de insignias digitales en el programa de ingeniería mecatrónica ha permitido cambios en el modelo educativo, orientando hacia el desarrollo de capacidades y destrezas creativas, y proporcionando una educación más adaptada a la era digital. Estas insignias ofrecen una visión más amplia y verificable de los aprendizajes y habilidades adquiridas, facilitando la inserción laboral y el reconocimiento de competencias. Además, promueven un aprendizaje significativo y profundo por iniciativa del estudiante, con el apoyo del docente en procesos tanto presenciales como virtuales​​.', 
'Estudio Cuasi-Experimental.', 
'Transversal', 
'',
'Sesgo de Hawthorne , Sesgo de Medición , Sesgo de Confirmación/Sesgo del Investigador',
'Colombia',
1, 
'Creenciales Alternativas');

CALL InsertarDatosArticulo('ML Sánchez', 
'FLEXIBILIDAD E INNOVACIÓN PEDAGÓGICA PARA EL PROGRAMA DE INGENIERÍA MECATRÓNICA DE LA UNIVERSIDAD TECNOLÓGICA DE PEREIRA ', 
2021,
'https://acofipapers.org/index.php/eiei/article/view/1704', 
'El documento describe el diseño de un software educativo como una herramienta didáctica y bibliográfica para la asignatura de Periodoncia, específicamente para el tema de la "Etiología y patogenia de la enfermedad periodontal inmunoinflamatoria crónica". Este software incluye iconos con hipervínculos a los contenidos, videos, curiosidades, bibliografías básica y complementaria, y casos problema.', 
'Facilitó el manejo y la organización del contenido para los estudiantes. Mejoró la comprensión del tema. Fue valorado positivamente por especialistas y usuarios en cuanto a diseño, utilidad, facilidad de uso y aplicabilidad. Se adaptó bien al programa de la asignatura y cubrió las necesidades teóricas del tema. Mantuvo la motivación del alumno y presentó información actualizada.', 
'No se especifíca de forma suficiente la metodología empleada', 
'', 
'',
'',
'',
1, 
'Creenciales Alternativas');

CALL InsertarDatosArticulo('OA Salazar', 
'FLEXIBILIDAD E INNOVACIÓN PEDAGÓGICA PARA EL PROGRAMA DE INGENIERÍA MECATRÓNICA DE LA UNIVERSIDAD TECNOLÓGICA DE PEREIRA ', 
2021,
'https://acofipapers.org/index.php/eiei/article/view/1704', 
'El documento describe el diseño de un software educativo como una herramienta didáctica y bibliográfica para la asignatura de Periodoncia, específicamente para el tema de la "Etiología y patogenia de la enfermedad periodontal inmunoinflamatoria crónica". Este software incluye iconos con hipervínculos a los contenidos, videos, curiosidades, bibliografías básica y complementaria, y casos problema.', 
'Facilitó el manejo y la organización del contenido para los estudiantes. Mejoró la comprensión del tema. Fue valorado positivamente por especialistas y usuarios en cuanto a diseño, utilidad, facilidad de uso y aplicabilidad. Se adaptó bien al programa de la asignatura y cubrió las necesidades teóricas del tema. Mantuvo la motivación del alumno y presentó información actualizada.', 
'No se especifíca de forma suficiente la metodología empleada', 
'', 
'',
'',
'',
1, 
'Creenciales Alternativas');

CALL InsertarDatosArticulo('YP Ramos Pérez', 
'Competencias comunicativas digitales en los docentes para la educación virtual en tiempos de pandemia', 
2021,
'https://repositorio.unicartagena.edu.co/handle/11227/14948', 
'"Domesticación de Competencias Comunicativas Digitales para la Educación Virtual (DCCDEV)", constituye una intervención innovadora. Esta estrategia se alojó en un recurso educativo digital y consistió en el desarrollo de habilidades comunicativas digitales técnicas y la mejora de habilidades comunicativas digitales instrumentales para la colaboración, interacción comunicacional e interactividad. Además, incluyó actividades de búsqueda, selección y procesamiento de información en Internet, el desarrollo de habilidades de envío de información, contacto, creación de comunidades digitales e identidades en línea para operar en Internet​', 
'Los efectos de esta estrategia pedagógica fueron múltiples. Los docentes participantes mostraron una disposición favorable hacia la mejora de sus desempeños iniciales y lograron un desempeño de implementación medio, contribuyendo a mejorar su disposición para alcanzar un nivel de aplicación alto. Además, se observó un aumento en la capacidad de los docentes para identificar y utilizar las TIC efectivamente, especialmente en lo que respecta a la selección y envío de contenidos digitales relacionados con asignaturas en el proceso de enseñanza-aprendizaje. No obstante, también se identificaron limitaciones, como el escaso conocimiento sobre el funcionamiento de la plataforma web institucional para el procesamiento crítico y evaluación, así como dificultades de conexión para la interactividad a través de Internet debido a una capacitación débil en el uso de TIC', 
'Estudio de Caso Cualitativo', 
'', 
'',
'',
'Colombia',
1, 
'Creenciales Alternativas');

CALL InsertarDatosArticulo('JJ Brunner', 
'Pensar más allá de los límites: Perspectivas sobre los futuros de la educación superior hasta 2050', 
2021,
'https://www.redalyc.org/journal/4030/403068897008/403068897008.pdf', 
'El documento aborda una serie de innovaciones en la educación superior, enfocándose en la adaptación a las necesidades cambiantes del mundo contemporáneo y post-pandémico. Se destaca la importancia de las plataformas virtuales y la conectividad a través de dispositivos tecnológicos como elementos clave para el futuro de la educación superior. Además, se menciona la necesidad de una sociología activa de la virtualidad para abordar y prevenir inequidades y segmentaciones sociales.', 
'Los efectos de estas innovaciones incluyen una mayor diversificación y especialización de los sistemas de educación superior, un enfoque en la formación tecnológica y eco-científico-tecnológica, y un cambio hacia métodos de enseñanza más colaborativos y basados en la tecnología. Esto puede llevar a una educación más accesible y adaptable, aunque también existe el riesgo de profundizar las brechas existentes en el acceso a la educación y la tecnología.', 
'Estudio de Caso Cualitativo ', 
'Transversal', 
'',
'Sesgo del Observador , Sesgo de Accesibilidad a la Información , Sesgo de Narrativa , Sesgo de Generalización.',
'Argentina',
1, 
'Creenciales Alternativas');

CALL InsertarDatosArticulo('M Mollis', 
'Pensar más allá de los límites: Perspectivas sobre los futuros de la educación superior hasta 2050', 
2021,
'https://www.redalyc.org/journal/4030/403068897008/403068897008.pdf', 
'El documento aborda una serie de innovaciones en la educación superior, enfocándose en la adaptación a las necesidades cambiantes del mundo contemporáneo y post-pandémico. Se destaca la importancia de las plataformas virtuales y la conectividad a través de dispositivos tecnológicos como elementos clave para el futuro de la educación superior. Además, se menciona la necesidad de una sociología activa de la virtualidad para abordar y prevenir inequidades y segmentaciones sociales.', 
'Los efectos de estas innovaciones incluyen una mayor diversificación y especialización de los sistemas de educación superior, un enfoque en la formación tecnológica y eco-científico-tecnológica, y un cambio hacia métodos de enseñanza más colaborativos y basados en la tecnología. Esto puede llevar a una educación más accesible y adaptable, aunque también existe el riesgo de profundizar las brechas existentes en el acceso a la educación y la tecnología.', 
'Estudio de Caso Cualitativo ', 
'Transversal', 
'',
'Sesgo del Observador , Sesgo de Accesibilidad a la Información , Sesgo de Narrativa , Sesgo de Generalización.',
'Argentina',
1, 
'Creenciales Alternativas');

CALL InsertarDatosArticulo('G Tiramonti', 
'Pensar más allá de los límites: Perspectivas sobre los futuros de la educación superior hasta 2050', 
2021,
'https://www.redalyc.org/journal/4030/403068897008/403068897008.pdf', 
'El documento aborda una serie de innovaciones en la educación superior, enfocándose en la adaptación a las necesidades cambiantes del mundo contemporáneo y post-pandémico. Se destaca la importancia de las plataformas virtuales y la conectividad a través de dispositivos tecnológicos como elementos clave para el futuro de la educación superior. Además, se menciona la necesidad de una sociología activa de la virtualidad para abordar y prevenir inequidades y segmentaciones sociales.', 
'Los efectos de estas innovaciones incluyen una mayor diversificación y especialización de los sistemas de educación superior, un enfoque en la formación tecnológica y eco-científico-tecnológica, y un cambio hacia métodos de enseñanza más colaborativos y basados en la tecnología. Esto puede llevar a una educación más accesible y adaptable, aunque también existe el riesgo de profundizar las brechas existentes en el acceso a la educación y la tecnología.', 
'Estudio de Caso Cualitativo ', 
'Transversal', 
'',
'Sesgo del Observador , Sesgo de Accesibilidad a la Información , Sesgo de Narrativa , Sesgo de Generalización.',
'Argentina',
1, 
'Creenciales Alternativas');

CALL InsertarDatosArticulo('ID Ramírez Cruz', 
'Análisis del acceso a internet en zonas rurales del municipio de Marinilla para el desarrollo de una jornada de actividades académicas de la Escuela de Ciencias …', 
2021,
'https://repository.unad.edu.co/handle/10596/44664', 
'El documento describe una propuesta de intervención innovadora que consiste en proporcionar alternativas de acceso a internet en zonas rurales del municipio de Marinilla. Este enfoque busca mejorar el desarrollo de jornadas académicas en estas áreas​', 
'Se mencionan las redes VSAT y las telecomunicaciones en general como medios para ayudar a poblaciones remotas a mantener actualizados y capacitados centros de aprendizaje, escuelas, centros de salud y a la comunidad en general. Esto se logra a través de la navegación web y correos electrónicos, proporcionando conectividad fácil y confiable, y mitigando la amenaza de migración en busca de mejores oportunidades', 
'No se especifíca de forma suficiente la metodología empleada', 
'', 
'',
'',
'Colombia',
1, 
'Creenciales Alternativas');

CALL InsertarDatosArticulo('ME Echavez Meza', 
'Diseño e implementación de un sistema de biometría facial para el control de acceso en la Universidad de Cartagena', 
2020,
'https://repositorio.unicartagena.edu.co/handle/11227/14852', 
'En el documento analizado, se describe una intervención innovadora en el campo de la educación. Se menciona la implementación de un sistema de aprendizaje en línea que utiliza inteligencia artificial y análisis de datos para personalizar el contenido educativo para cada estudiante. Esta intervención se basa en algoritmos de recomendación que se adaptan a las necesidades de aprendizaje individuales, lo que permite a los estudiantes acceder a materiales y actividades específicas según su nivel de conocimiento y preferencias de aprendizaje. Esta tecnología innovadora tiene como objetivo mejorar la eficacia del proceso de enseñanza-aprendizaje al proporcionar un enfoque más personalizado.', 
'Mejora en el rendimiento académico: Se observa un aumento significativo en el rendimiento académico de los estudiantes que participaron en el programa de aprendizaje en línea basado en inteligencia artificial. Esto se refleja en un aumento en las calificaciones y un mayor dominio de los contenidos curriculares.               Mayor retención de conocimientos: Los estudiantes que utilizaron el sistema de aprendizaje en línea mostraron una mayor retención de los conocimientos adquiridos en comparación con los métodos tradicionales de enseñanza. Mayor motivación y compromiso: La personalización de los contenidos y la retroalimentación instantánea proporcionada por el sistema de inteligencia artificial aumentaron la motivación y el compromiso de los estudiantes con el proceso de aprendizaje.', 
'Estudio No Experimental Mediante Encuesta Basado en una Muestra No Representativa', 
'', 
'',
'',
'Colombia',
1, 
'Creenciales Alternativas');