CALL InsertarDatosArticulo('E Muñoz Cuchca', 
'Enfoque cualitativo y cuantitativo de la evaluación formativa', 
2021,
'http://scielo.senescyt.gob.ec/scielo.php?pid=S2550-65872021000300001&script=sci_arttext', 
'El documento describe una intervención innovadora en el ámbito de la evaluación en la educación superior. Esta intervención consiste en la integración de enfoques cuantitativos y cualitativos en el marco de una evaluación formativa. Este enfoque mixto aborda las limitaciones de la evaluación cuantitativa y las ventajas de la evaluación cualitativa, proponiendo una síntesis que permite una mejor toma de decisiones y contribuye de manera más efectiva al proceso de aprendizaje y enseñanza​', 
'La integración de enfoques cuantitativos y cualitativos en la evaluación formativa tiene como efecto principal la creación de una evaluación mixta que favorece el proceso de aprendizaje y enseñanza. Esta integración lleva a una descripción e interpretación más rica y contextualizada de los logros de los estudiantes, permitiendo a los educadores tomar decisiones más informadas y eficaces para mejorar el proceso educativo​', 
'Revisión bibliográfica', 
'Transversal', 
'Sesgo de Selección de Estudios, Sesgo de Heterogeneidad',
'Sesgo de Extracción de Datos, Sesgo de Confirmación, Sesgo de Citación',
'Perú',
10, 
'Productividad');

CALL InsertarDatosArticulo('LI Castañeda-Rentería, E Araujo', 
'Atrapadas en casa: maternidad (es), ciencia y COVID-19', 
2021,
'https://brajets.com/v3/index.php/brajets/article/view/754', 
'El documento describe una intervención innovadora en el contexto de la educación superior, centrada en la evaluación en contextos de aula invertida. Esta intervención se caracteriza por su enfoque pedagógico y las posibilidades didácticas de las actividades, que definen la impronta de la evaluación más que las cualidades de las herramientas tecnológicas utilizadas', 
'La intervención mencionada en el documento tiene efectos significativos en el proceso educativo. Las actividades de evaluación, que incluyen tanto componentes presenciales como virtuales (tareas, foros, cuestionarios), permiten un seguimiento continuo del aprendizaje de los estudiantes. Esto incluye la comprensión del material, la aplicación de conocimientos a situaciones reales y la integración de saberes. Además, la necesidad de un examen final para certificar el aprendizaje adquirido en la unidad temática es también un aspecto clave de esta intervención​', 
'Estudio de Caso Cualitativo', 
'Transversal', 
'',
'Sesgo del Observador, Sesgo de Narrativa, Sesgo de Generalización',
'Argentina',
9, 
'Productividad');

CALL InsertarDatosArticulo('JJ Borja Granados, RD García Caballero', 
'Evaluación formativa oportunidad en el proceso de enseñanza aprendizaje en el área de matemáticas en tiempos de pandemia', 
2021,
'https://repositorio.cuc.edu.co/handle/11323/8507', 
'El documento describe una intervención innovadora en el contexto de la evaluación durante la pandemia de COVID-19. Se centra en la evaluación de profesores universitarios de Colombia, México y Perú que participaron en un curso de formación en modalidad virtual. Esta intervención adopta un enfoque mixto, utilizando una encuesta validada por expertos para indagar aspectos de la evaluación en un entorno virtual de aprendizaje asincrónico. Se identificaron cuatro variables: evaluación habitual, evaluación habitual en crisis, evaluación continua y formativa, y evaluación con recursos tecnológicos. La principal innovación radica en adaptar la evaluación a un entorno virtual y asincrónico, abordando las limitaciones y desafíos planteados por la pandemia.', 
'Los efectos de esta intervención incluyen el predominio de la evaluación tradicional pero con la identificación de la necesidad de cambios en su fundamento y realización. Se destacan aspectos como la crisis de la evaluación habitual debido a las limitaciones del entorno virtual, la necesidad de una evaluación continua y formativa, y la integración de tecnologías en el proceso de evaluación. Estos cambios reflejan una adaptación y respuesta a los desafíos impuestos por el contexto de la pandemia.', 
'No se especifíca de forma suficiente la metodología empleada', 
'Transversal', 
'',
'',
'Colombia, México, Perú',
4, 
'Productividad');

CALL InsertarDatosArticulo('D Benavides-Arias, D Soler-Tovar', 
'Evaluación prospectiva de las iniciativas en contra de las zoonosis de países de América Latina', 
2021,
'http://www.scielo.org.co/scielo.php?pid=S0124-00642021000400009&script=sci_arttext', 
'Intervención Innovadora: El documento describe una intervención innovadora en el contexto de la educación superior, enfocándose en la "Evaluación Formativa". Esta intervención es considerada una alternativa a los métodos tradicionales de evaluación, que usualmente se centran más en la calificación que en la retroalimentación. La Evaluación Formativa se integra en las secuencias de aprendizaje, facilita momentos de contingencia y regulación, permite la participación activa del estudiante en su aprendizaje, reconoce la diferenciación pedagógica, proporciona información y evidencia para la regulación, posibilita el uso de diversos medios de recolección de información, y se desarrolla de forma contextualizada. Este enfoque promueve la autonomía del alumnado y su autorregulación, convirtiéndolo en una parte activa del proceso evaluativo, incluyendo la autoevaluación y la evaluación por pares.', 
'Se menciona que la Evaluación Formativa tiene un impacto positivo en el aprendizaje, detectando errores a tiempo y mejorando el proceso formativo. Va más allá de lo académico, incidiendo en la formación personal del educando. Estudios citados en el documento, como los de Hattie (1992), sugieren que el cambio en el rendimiento académico puede ser significativamente influenciado por la retroalimentación ofrecida a través de este enfoque.', 
'Estudio de Caso Cualitativo', 
'Transversal', 
'Sesgo del Observador',
'Sesgo de Selección del Caso, Sesgo de Accesibilidad a la Información, Sesgo Temporal, Sesgo de Narrativa, Sesgo de Generalización',
'Colombia ',
3, 
'Productividad');

CALL InsertarDatosArticulo('E Sánchez Almodóvar, J Olcina, J Martí Talavera', 
'La enseñanza del clima, el cambio climático y los extremos atmosféricos: Propuestas para la ciudadanía desde la universidad', 
2022,
'https://rua.ua.es/dspace/bitstream/10045/130307/1/Sanchez-Almodovar_etal_EGRR_1ed-2022.pdf', 
'La intervención innovadora descrita en el documento se centra en la "evaluación formativa en el proceso de enseñanza y aprendizaje durante la pandemia de COVID-19". Esta evaluación se realizó a través de la retroalimentación oportuna, lo cual fue un método efectivo para valorar los desempeños de los estudiantes. Esta metodología implicó el uso de autoevaluación, autonomía, motivación y reflexión para mejorar el aprendizaje de los estudiantes', 
'Los efectos de esta intervención incluyen la reestructuración de los sistemas de conocimiento y las habilidades cognitivas, permitiendo a los estudiantes adquirir nuevos conocimientos, habilidades y actitudes. La retroalimentación facilitó la incorporación de elementos teóricos y favoreció la reflexión. Permitió también devoluciones oportunas y personalizadas o en pequeños grupos a los estudiantes, basadas en sus evidencias de aprendizaje, con la finalidad de que identifiquen sus aciertos y errores para mejorar su aprendizaje', 
'Revisión bibliográfica', 
'Transversal', 
'Sesgo de Calidad Metodológica, Sesgo de Heterogeneidad',
'Sesgo de Publicación, Sesgo de Idioma, Sesgo de Selección de Estudios',
'Perú',
2, 
'Productividad');

CALL InsertarDatosArticulo('DS Aguilar Ruffner, KS Cabanillas Costa', 
'Factores motivacionales y su relación con el desempeño laboral en la empresa Transportes R&D EIRL, en la ciudad de Piura, 2021', 
2022,
'https://repositorio.upn.edu.pe/handle/11537/30439', 
'Intervención Innovadora Descrita: El documento describe una intervención en el ámbito de la evaluación y acreditación de instituciones de educación superior (IES) en varios países de América Latina, como México, Ecuador, Perú, Chile, Cuba, Argentina y Colombia. Se enfoca en el proceso de evaluación y acreditación, considerando la organización y planificación previa, la ejecución y los resultados obtenidos. La evaluación se realiza a través de criterios que incluyen subcriterios sustentados en indicadores cualitativos y cuantitativos, guiados por normas como las ISO 9000. Los aspectos evaluados abarcan desde la formación profesional, producción científica y tecnológica, hasta la gestión y dirección universitarias. Este proceso se considera una estrategia importante para el control, seguimiento y legitimación de las IES, generando confianza y contribuyendo a su prestigio y credibilidad​', 
'La intervención ha generado diversos efectos en las IES. Se destaca la importancia de la evaluación como un medio para garantizar la eficiencia y calidad de las instituciones educativas. Esta evaluación y acreditación son vistas como necesarias para el buen funcionamiento y la legitimación de las IES. Además, se señala que el proceso de evaluación y acreditación puede llevar a grandes transformaciones en las instituciones, siempre y cuando se mantenga un enfoque en la calidad. Estos procesos son considerados clave para la credibilidad y el prestigio de las IES', 
'Revisión Bibliográfica', 
'Transversal', 
'Sesgo de Heterogeneidad',
'Sesgo de Publicación, Sesgo de Idioma, Sesgo de Calidad Metodológica, Sesgo de Confirmación, Sesgo de Citación',
'México, Ecuador, Perú, Chile, Cuba, Argentina y Colombia',
1, 
'Productividad');

